'use strict';
// Art for the second wave of foes: four more per land. Colour pixels only, then an
// automatic '0' outline; light from the top left.
(function foes() {
  const o = { flip: true, flash: true, glow: true };
  const F = (name, art) => def(name, autoOutline(parseArt(name, art)), o);

  // ---------- Bloom Meadow ----------
  // Bunny: sits, then bounds in quick hops.
  F('bunny_0', `
    ..............
    ...L....L.....
    ...Lq...Lq....
    ...Lq...Lq....
    ...LLl..LLl...
    ..LLLLLLLLLl..
    ..LLrLLLrLLl..
    ..LLLLqqLLLl..
    ..lLLLLLLLll..
    ...lLLLLLll...
    ...lll..lll...
    ..............`);
  F('bunny_1', `
    ..............
    ....L....L....
    ....Lq...Lq...
    ...LLl..LLl...
    ..LLLLLLLLLl..
    ..LLrLLLrLLl..
    ..LLLLqqLLLl..
    ..lLLLLLLLll..
    ...lLLLLLll...
    ..ll......ll..
    .ll........ll.
    ..............`);
  // Snail: its shell stops shots from the front.
  F('snail_0', `
    ................
    .......NNNN.....
    ......NOOOONn...
    .....NOnnnnONn..
    .....NOnOONONn..
    .....NOnOnnONn..
    .c...NOnnnOONn..
    ..c...NOOOONn...
    ..hhh..nnnnn....
    .hhh0hGGGGGGGg..
    .hhhhhhhhhhhhGg.
    ..ggggggggggggg.
    ................`);
  F('snail_1', `
    ................
    .......NNNN.....
    ......NOOOONn...
    .....NOnnnnONn..
    .....NOnOONONn..
    .c...NOnOnnONn..
    ..c..NOnnnOONn..
    ..hh..NOOOONn...
    .hhhh..nnnnn....
    .hh0hhGGGGGGGGg.
    ..hhhhhhhhhhhhGg
    ...gggggggggggg.
    ................`);
  // Dandelion: rooted; puffs out drifting seeds.
  F('dandelion_0', `
    ................
    .....LwLLw......
    ...LwLLLLLLl....
    ..LLLLLLLLLLl...
    ..wLLLyyyLLLl...
    ..LLLyYyyyLLl...
    ..LLLyyyyoLLl...
    ..lLLLyyoLLll...
    ...lLLLLLLll....
    .....llll.......
    .......g........
    ...hG..g........
    ...hGG.g..Gg....
    ....GggggGg.....
    ................`);
  F('dandelion_1', `
    ................
    ..w..w....w.....
    ....LLLLL...w...
    ..LLLLLLLLl.....
    .LLLLyyyLLLl..w.
    .LLLyYyyyLLl....
    .LLLyyyyoLLl....
    .lLLLyyoLLll....
    ..lLLLLLLll.....
    ....llll........
    .......g........
    ...hG..g........
    ...hGG.g..Gg....
    ....GggggGg.....
    ................`);
  // Ladybug: flies over the hero and drops spots that linger.
  F('ladybug_0', `
    ................
    ..CC......CC....
    .CwwC....CwwC...
    ..CCC....CCC....
    ....RRRRRR......
    ...RqR1RRRr.....
    ..RRR11RR1Rr....
    ..R1RRR1RRRr....
    ..RRRRRRR1rr....
    ...rRR1Rrrr.....
    ...21rrrr12.....
    ....2....2......
    ................`);
  F('ladybug_1', `
    ................
    ................
    ................
    ...CCCCRRRCCC...
    ..CwwRRqRRRwwC..
    ...RqR1RRRrCC...
    ..RRR11RR1Rr....
    ..R1RRR1RRRr....
    ..RRRRRRR1rr....
    ...rRR1Rrrr.....
    ...21rrrr12.....
    ....2....2......
    ................`);

  // ---------- Sunny Shore ----------
  // Seagull: circles high, then dives along a line.
  F('gull_0', `
    ..................
    .LL............LL.
    .lLL..........LLl.
    ..lLLL......LLLl..
    ...llLLLLLLLLll...
    .....LLLLLLl......
    ....LL0LLLLlOO....
    ....LLLLLLLlo.....
    .....lLLLLll......
    ......llll........
    ..................`);
  F('gull_1', `
    ..................
    ..................
    ..................
    .....LLLLLLl......
    ....LL0LLLLlOO....
    .lLLLLLLLLLLLLLl..
    ..mllLLLLLLLllm...
    ....mm.lllll.mm...
    .......llll.......
    ..................
    ..................`);
  // Starfish: skids around like a billiard ball.
  F('starfish_0', `
    ................
    .......R........
    ......RRo.......
    ......ROo.......
    .RRRRRRRRRooo...
    ..ROOROOROOo....
    ...RR0OO0Oo.....
    ....ROOOOo......
    ...ROOoOOOo.....
    ..ROo....ROo....
    ..Ro......oo....
    ................`);
  F('starfish_1', `
    ................
    ................
    .......R........
    ......RRo.......
    ..RRRRRRRRooo...
    ...ROR0OO0oo....
    ....ROOOOOo.....
    ...ROOoOOOo.....
    ..ROo....ROo....
    .Roo......Roo...
    ................
    ................`);
  // Pufferfish: puffs up when you come close, then bursts into spikes.
  F('puffer_0', `
    ................
    ................
    ....YYYYY.......
    ...YyyyyyO......
    ..YYywyyyyO.T...
    ..Yyy0yyyyOTT...
    ..YyyyyyyyOTt...
    ..yyyRyyyoO.t...
    ...yyyyyoO......
    ....oooOO.......
    ................
    ................`);
  F('puffer_1', `
    ...y..y..y......
    .y.YYYYYYYy.....
    ..YyyyyyyyOO....
    .YYywwyyyyyOy...
    yYyyy0yyyyyO.T..
    .Yyyyyyyyyy0TT..
    yYyyyRRyyyyOTt..
    .yyyyyyyyyoO..t.
    ..yyyyyyyooO....
    .y.oooooooo.y...
    ...o..o..o......
    ................`);
  // Hermit crab: hides in its shell, then pops out with a fan of bubbles.
  F('hermit_0', `
    ................
    ......qqqq......
    .....qPPPPq.....
    ....qPpPPpPp....
    ....qPPppPPp....
    ...qPPPPPPPpp...
    ...PpPPpPPpPp...
    ...ppppppppppp..
    .RRR.R0RR0R.RRR.
    .RRr.RRRRRR.RRr.
    ..rr..r..r..rr..
    ................`);
  F('hermit_1', `
    ................
    ................
    ................
    ......qqqq......
    .....qPPPPq.....
    ....qPpPPpPp....
    ....qPPppPPp....
    ...qPPPPPPPpp...
    ...PpPPpPPpPp...
    ...ppppppppppp..
    ................
    ................`);

  // ---------- Crystal Cave ----------
  // Mole: burrows, then pops up next to you.
  F('mole_0', `
    ................
    .....NNNNN......
    ....NNNNNNn.....
    ...NN0NN0NNn....
    ...NNNqqNNNn....
    ...NNqPPqNNn....
    ..AANNqqNNnAA...
    ..AaNNNNNNnaA...
    ...NNNNNNNNn....
    ..mlmNNNNnmlm...
    .mlllmmmmmllm...
    ................`);
  F('mole_1', `
    ................
    ................
    ................
    ................
    ................
    ......m.l.......
    ....m.l..m......
    ...mlmllmlm.....
    ..mllmlllmlm....
    .mllllmlllllm...
    .mmmmmmmmmmmm...
    ................`);
  // Crystal spider: drops on a thread and spits webs.
  F('spider_0', `
    ................
    ..3..........3..
    ...3..4333..3...
    ....3433332.3...
    .33.3333332..33.
    ...3332w32w32...
    ..3.2222222223..
    .3...2222221..3.
    ....3.21112.3...
    ...3..3...3..3..
    ................`);
  F('spider_1', `
    ................
    ................
    .3....4333....3.
    ..3..4333332.3..
    ...333333332.3..
    .3.3332w32w323..
    ...32222222223..
    ..3..2222221.3..
    .3..3.21112..3..
    .....3.....3....
    ................`);
  // Gemlet: a small crystal golem that stomps rings of shards.
  F('gemlet_0', `
    ................
    ......CC........
    .....CwCc.......
    ....CCCCcB......
    ...lLLLLLLl.....
    ..lLLc0Lc0Lm....
    ..lLLLLLLLLm....
    ..lLLLLLLLmm....
    .CclLLLLLLmBb...
    .cB.llmmmm.bB...
    ....lm..lm......
    ....mm..mm......
    ................`);
  F('gemlet_1', `
    ................
    ................
    ......CC........
    .....CwCc.......
    ....CCCCcB......
    ...lLLLLLLl.....
    .ClLLc0Lc0LmB...
    CclLLLLLLLLmBb..
    c.lLLLLLLLmm.b..
    ...llLLLLmm.....
    ...lm....lm.....
    ..mmm....mmm....
    ................`);
  // Glow moth: flutters about and leaves clouds of glowing dust.
  F('gmoth_0', `
    ..................
    .44.....3.....44..
    .4w4.....3...4w4..
    .44344..yy..44343.
    ..4w334yYyy43w43..
    ...4334yyyo4333...
    ..43334yyyo43333..
    ..4333.yyoo.3332..
    ...33...yo...32...
    ..................`);
  F('gmoth_1', `
    ..................
    ........3.........
    .........3........
    ....44..yy..443...
    ..44w44yYyy44w43..
    .4w33344yyo433332.
    ..44333yyyo333322.
    ....44.yyoo.322...
    ........yo........
    ..................`);
})();
