'use strict';
// Art for the progress systems: tutorial props, pickups and icons added after the first
// release. Same rules as the other art files: PAL colours only, '0' outlines, light from
// the top left.

// ---------- Practice dummy (tutorial): a straw target on a post ----------
(function dummy() {
  const make = (dx) => {
    const g = grid(16, 21);
    g.fill((x, y) => {
      const cx = 7.5 + dx, cy = 7.5, ddx = x + 0.5 - cx, ddy = y + 0.5 - cy, d = Math.hypot(ddx, ddy);
      if (d > 6.6) return null;
      const lit = ddx + ddy < -1.5, dark = ddx + ddy > 3;
      if (d <= 1.7) return lit ? 'Y' : 'y';
      if (d <= 3.4) return lit ? 'R' : dark ? 'p' : 'r';
      if (d <= 5.0) return lit ? 'w' : dark ? 'l' : 'L';
      return lit ? 'R' : dark ? 'p' : 'r';
    });
    for (let y = 14; y <= 18; y++) g.px(7, y, 'N').px(8, y, 'n');
    g.line(5, 18, 10, 18, 'N').line(4, 19, 11, 19, 'n');
    return autoOutline(g.rows());
  };
  def('dummy_0', make(0), { flash: true });
  def('dummy_1', make(1), { flash: true });
})();

// ---------- Garden menu icons (16x16, colour pixels, then an automatic outline) ----------
(function gardenIcons() {
  const I = (name, rows) => def('icon_' + name, autoOutline(parseArt(name, rows)), { sil: '1' });
  // UPGRADES: a sprout in a clay pot
  I('sprout', `
    ................
    ......hh........
    .....hHGg..hh...
    ....hHGGg.hHGg..
    ....GGgg.hHGGg..
    .....gg.hGGgg...
    ......g.gGg.....
    .......gg.......
    .......g........
    ....NNNNNNNn....
    ....OOOOOOOn....
    .....NNNNNn.....
    .....NNNNnn.....
    ......Nnnn......
    ................
    ................`);
  // QUESTS: a scroll with a green tick
  I('quest', `
    ................
    ..NNNNNNNNNNNN..
    ..nnnnnnnnnnnn..
    ...AAAAAAAAAa...
    ...Aaeeeeaaae...
    ...Aaaaaaaaae...
    ...Aaeeeaaahe...
    ...AaaaaaahGe...
    ...AheaaahGae...
    ...AGhaahGaae...
    ...AaGhhGaaae...
    ...AaaGGaaaae...
    ...Aaaaaaaaae...
    ..NNNNNNNNNNNN..
    ..nnnnnnnnnnnn..
    ................`);
  // CONSTELLATIONS: a telescope on a stand, with a star
  I('scope2', `
    ............Y...
    ...........YwY..
    ..........CY.Y..
    .........CCc....
    ........CBBb....
    .......cBBbb....
    ......cBBbb.....
    .....cBBbb......
    ....cBBbb.......
    ....BBbb........
    ....bbbN........
    ......NnN.......
    .....N.n.N......
    ....N..n..n.....
    ...N...n...n....
    ................`);
  // BOOK: a red book with a gold star
  I('book', `
    ................
    ...RRRRRRRRRr...
    ..RRRrrrrrrrrp..
    ..RrrrryYrrrrp..
    ..Rrrrryyrrrrp..
    ..RrrYyyyyyrrp..
    ..Rrrryyyyrrrp..
    ..Rrrryrryrrrp..
    ..Rrrrrrrrrrrp..
    ..Rrrrrrrrrrrp..
    ..Rrrrrrrrrrrp..
    ..RrrrrrrrrrrpL.
    ..ppppppppppppL.
    ...LLLLLLLLLLLl.
    ................
    ................`);
  // MAILBOX: a letter with a heart seal
  I('mail', `
    ................
    ................
    ................
    ..LLLLLLLLLLLL..
    ..LlLLLLLLLLlm..
    ..LLlLLLLLLlLm..
    ..LLLlLLLLlLLm..
    ..LLLLlrrlLLLm..
    ..LLLLrRRrLLLm..
    ..LLLLLrrLLLLm..
    ..LLLlLLLLlLLm..
    ..LLlLLLLLLlLm..
    ..mmmmmmmmmmmm..
    ................
    ................
    ................`);
})();

// ---------- Pets: little friends that follow the hero (two frames each) ----------
(function pets() {
  const o = { flip: true };
  def('pet_bun_0', autoOutline(parseArt('bun0', `
    ............
    ...LL.LL....
    ...Lq.Lq....
    ...Lq.Lq....
    ..LLLLLLL...
    .LLL0LL0Ll..
    .LLLLqqLLl..
    .LLLLLLLLl..
    ..lLLLLLl...
    ...ll.ll....
    ............`)), o);
  def('pet_bun_1', autoOutline(parseArt('bun1', `
    ............
    ............
    ...LL.LL....
    ...Lq.Lq....
    ..LLLLLLL...
    .LLL0LL0Ll..
    .LLLLqqLLl..
    .LLLLLLLLl..
    .llLLLLLll..
    ............
    ............`)), o);
  def('pet_bee_0', autoOutline(parseArt('pbee0', `
    ............
    ...CC.CC....
    ...CwwCw....
    ....CC.C....
    ...YYyyYy...
    ..YYy1y01o..
    ..yyy1yyRo..
    ...ooo1oo...
    ............`)), o);
  def('pet_bee_1', autoOutline(parseArt('pbee1', `
    ............
    ............
    ..CCw..CCw..
    ...CC..CC...
    ...YYyyYy...
    ..YYy1y01o..
    ..yyy1yyRo..
    ...ooo1oo...
    ............`)), o);
  def('pet_slime_0', autoOutline(parseArt('pslime0', `
    ............
    ............
    ....HHhh....
    ...HwHhhG...
    ..HHhhhhhG..
    ..hh0hh0hG..
    ..hhhhhhGg..
    ...gGGGgg...
    ............`)), o);
  def('pet_slime_1', autoOutline(parseArt('pslime1', `
    ............
    ............
    ............
    ...HHhhhh...
    ..HwHhhhhG..
    .hhh0hh0hGg.
    .hhhhhhhGgg.
    ..ggGGGggg..
    ............`)), o);
})();
