'use strict';
// UI art: HUD bits, cursor, minimap icons, upgrade icons, merchant, title logo.

def('heart_empty', `
  .00...00.
  0dmd0dmd0
  0mddddmd0
  0dddddmd0
  .0dddmd0.
  ..0dmd0..
  ...0d0...
  ....0....`);
def('cursor', `
  ...000...
  ...0w0...
  ...0w0...
  0000.0000
  0ww...ww0
  0000.0000
  ...0w0...
  ...0w0...
  ...000...`);
def('mm_boss', '0.0.0\n0y0y0\n0yyy0\n0yPy0\n00000'.replace(/\./g, '.'));
def('mm_item', '..0..\n.0y0.\n0yYy0\n.0y0.\n..0..');
def('mm_chal', 'l...l\n0l.l0\n.0l0.\n0y0y0\ny0.0y');
def('mm_shop', '.000.\n0yYy0\n0Yoy0\n0yyo0\n.000.');
def('key_cap', `
  .0000000.
  0LLLLLLl0
  0LLLLLLl0
  0LLLLLLl0
  0LLLLLLl0
  0LLLLLLl0
  0LLLLLLl0
  0lllllll0
  .0000000.`);

// ---------- Upgrade icons (16x16) ----------
(function icons() {
  const I = (name, rows) => def('icon_' + name, rows, { sil: '1' });
  const O = (art) => autoOutline(parseArt('icon', art));

  I('rapid', O(`
    ................
    .......YYYYy....
    ......YYYyy.....
    .....YYyyy......
    ....YYyyy.......
    ...YYyyyyyYYy...
    ........Yyyo....
    .......Yyyo.....
    ......Yyyo......
    ......Yyo.......
    .....Yyo........
    .....Yo.........
    ....yo..........
    ....o...........
    ................
    ................`));
  const STAR = `
    ................
    .......YY.......
    ......YYyy......
    ......Yyyo......
    .YYYYYyyyyyyyoo.
    ..YYyyyyyyyyyo..
    ...Yyy0yy0yyo...
    ....yy0yy0yo....
    ....yqyyyyqo....
    ...Yyyyyyyyyo...
    ...Yyyyooyyyo...
    ..Yyyo....oyyo..
    ..Yyo......ooo..
    ..yo........oo..
    ................
    ................`;
  I('big', O(STAR));
  const shot = parseArt('shot', `
    ...0...
    ..0Y0..
    00YwY00
    0YwwwY0
    00YwY00
    ..0Y0..
    ...0...`);
  let tri = new Array(16).fill('................');
  tri = stamp(tri, 0, 8, shot); tri = stamp(tri, 9, 8, shot); tri = stamp(tri, 4, 2, shot);
  I('triple', tri);
  I('bounce', stamp(sculpt(16, 16, [{ e: [8, 8.5, 6.5, 6.5], ramp: 'pPqw' }]), 2, 8, '0yyyyyyyyyyy\n.0ooooooooo0'.split('\n').map((r, i) => i ? '..' + r.slice(0, 10) : r).join('\n').replace(/^0/, '.')));
  const arrow = grid(16, 16);
  for (let i = 0; i <= 7; i++) { arrow.px(3 + i, 12 - i, 'N'); arrow.px(4 + i, 12 - i, 'n'); }
  for (let y = 1; y <= 5; y++) for (let x = 9 + y; x <= 14; x++) arrow.px(x, y, y === 1 || x === 9 + y ? 'L' : x === 14 ? 'm' : 'l');
  arrow.px(1, 10, 'q').px(2, 10, 'q').px(1, 11, 'P').px(2, 11, 'P').px(2, 12, 'P')
    .px(3, 13, 'P').px(4, 13, 'p').px(4, 14, 'p').px(5, 14, 'p');
  I('pierce', autoOutline(arrow.rows()));
  I('homing', O(`
    ................
    ....0.....0.....
    .....0...0......
    ......2222......
    .....2w22w2.....
    ..CC..2222..CC..
    .CwwC.1111.CwwC.
    .CCCC.1111.CCCC.
    ..CC.YYYYYY.CC..
    ....YHHHHHHY....
    ....YHwwHHHY....
    ....YHHHHHHY....
    .....YHHHHY.....
    ......YYYY......
    ................
    ................`));
  I('moon', autoOutline(grid(16, 16).fill((x, y) => {
    const a = (x - 7.5) ** 2 + (y - 8) ** 2, b = (x - 10.5) ** 2 + (y - 5.5) ** 2;
    if (a > 36 || b < 26) return null;
    return (x + y < 11) ? 'Y' : (x - y > -2 ? 'o' : 'y');
  }).px(12, 11, 'Y').px(11, 12, 'Y').px(13, 12, 'Y').px(12, 13, 'Y').px(12, 12, 'w').rows()));
  I('heart', O(`
    ................
    ................
    ...RRR....RRR...
    ..RwRRr..RRRrr..
    .RwwRRrrRRRRrrp.
    .RwRRrrrrrrrrrp.
    .RRrrrrrrrrrrpp.
    ..rrrrrrrrrrpp..
    ...rrrrrrrrpp...
    ....rrrrrrpp....
    .....rrrrpp.....
    ......rrpp......
    .......pG.......
    ......hGG.......
    .......G........
    ................`));
  I('speed', O(`
    ................
    ................
    .....YYYYY......
    .....RqRRr......
    ..ww.RqRRr......
    .wwCwRqRRr......
    .wCCwRqRRr......
    ..wCwRqRRr......
    ...wwRRRRrr.....
    .....RRRRRrr....
    .....RRRRRRRr...
    .....RRRRRRRRr..
    .....rrrrrrrrr..
    .....yyyyyyyyy..
    ................
    ................`));
  I('magnet', O(`
    ................
    ................
    .....RRRRRR.....
    ...RqRRRRRRrr...
    ..RqRRr..rRRrr..
    ..RqRr....rRrr..
    ..RqRr....rRrr..
    ..RqRr....rRrr..
    ..RqRr....rRrr..
    ..RqRr....rRrr..
    ..LLLl....LLLl..
    ..LLLl....LLLl..
    ..llll....llll..
    ................
    ................
    ................`));
  I('firework', O(`
    ................
    .......RR.......
    ......RRRr......
    ......qRRr......
    ..Y...LLLl...Y..
    ......LBBl......
    ......LccB......
    ......LLLl......
    ......LLLl......
    .....RLLLlr.....
    ....RRLLLlrr....
    ....RR.yy.rr....
    .......Oy.......
    ......y..O......
    ................
    ................`));
  I('honey', stamp(sculpt(16, 16, [
    { e: [8, 10, 6.5, 5.5], ramp: 'nNOY' }, { e: [8, 4.5, 5, 2], ramp: 'nNOY', hi: false }, { e: [8, 4.5, 3.5, 1], ramp: 'oyyY', hi: false },
  ]), 4, 5, 'yy.y\ny..y\ny...'));
  I('backshot', O(`
    ................
    ................
    ....0..0..0.....
    .....0.0.0......
    .....LLLLLL.....
    ...LLLBBBBLLl...
    ..LLLBbwwBBLLl..
    ..LLLBb00bBLll..
    ..LLlBbb0bBlll..
    ...LllBBBBlll...
    .....llllll.....
    ................
    ................
    ................
    ................
    ................`));
  I('clover', stamp(sculpt(16, 16, [
    { e: [5.5, 5.5, 3.5, 3.5], ramp: 'gGhH' }, { e: [10.5, 5.5, 3.5, 3.5], ramp: 'gGhH' },
    { e: [5.5, 10.5, 3.5, 3.5], ramp: 'gGhH' }, { e: [10.5, 10.5, 3.5, 3.5], ramp: 'gGhH' },
  ]), 11, 12, '.0..\n0g0.\n.0g0\n..0.'));
  const tel = grid(16, 16);
  for (let i = 0; i <= 8; i++) { tel.px(3 + i, 10 - i, 'Y'); tel.px(4 + i, 10 - i, 'y'); tel.px(4 + i, 11 - i, 'o'); }
  tel.px(12, 1, 'C').px(13, 1, 'c').px(13, 2, 'c').px(12, 2, 'B').px(14, 2, 'B').px(13, 3, 'B');
  tel.line(7, 8, 4, 14, 'n').line(8, 8, 11, 14, 'n');
  I('scope', autoOutline(tel.rows()));
  I('stardust', stamp(sculpt(16, 16, [{ e: [8, 10.5, 6, 5], ramp: '1234' }, { r: [5, 3, 6, 4, 1], ramp: '1234', hi: false }]),
    5, 0, '.Y..Y\nYwY..\n.Y.0.').map((r, y) => y === 5 ? r.slice(0, 4) + '0yyyyyy0'.slice(0, 8) + r.slice(12) : r));
  I('bag', stamp(stamp(sculpt(16, 16, [{ e: [8, 10.5, 6.5, 5], ramp: 'nNOA' }, { r: [5, 3, 6, 4, 1], ramp: 'nNOA', hi: false }]),
    5, 5, '0yyyyy0'), 6, 9, '.000.\n0yYy0\n0Yyo0\n.000.'));
  I('shield', stamp(sculpt(16, 16, [{ e: [8, 8, 7, 7], ramp: 'cCCC', hi: false }]), 3, 3, 'ww.\nw..\n...'));
})();

// ---------- Merchant: a friendly frog ----------
def('frog_0', `
  ..0000....0000..
  .0wwwG0..0wwwG0.
  .0w00G0000w00G0.
  .0GGGGGGGGGGGgg0
  0hGGGGGGGGGGGGg0
  0hGqGGGGGGGGqGg0
  0hGG0GGGGGG0Ggg0
  .0GGG000000GGg0.
  ..0GGGGGGGGGg0..
  .0yYyyyyyyyyyo0.
  0GG0yyyyyyyyo0g0
  0GGG0yyyyyyo0gg0
  .0GG0HHHHHHH0g0.
  ..00.0HHHHH0.00.
  .....0000000....
  ................`, { flip: true });
def('frog_1', `
  ................
  ..0000....0000..
  .0wwwG0..0wwwG0.
  .0w00G0000w00G0.
  .0GGGGGGGGGGGgg0
  0hGGGGGGGGGGGGg0
  0hGqGGGGGGGGqGg0
  0hGG0GGGGGG0Ggg0
  .0GGG000000GGg0.
  .0yYyyyyyyyyyo0.
  0GG0yyyyyyyyo0g0
  0GGG0yyyyyyo0gg0
  .0GG0HHHHHHH0g0.
  ..00.0HHHHH0.00.
  .....0000000....
  ................`, { flip: true });

// ---------- Title logo letters (chunky, 12 px tall; only those in the title) ----------
const LOGO = {
  C: ['..xxxxxx..', '.xxxxxxxxx', 'xxxx....xx', 'xxx.......', 'xxx.......', 'xxx.......', 'xxx.......', 'xxx.......', 'xxx.......', 'xxxx....xx', '.xxxxxxxxx', '..xxxxxx..'],
  S: ['..xxxxxxx.', '.xxxxxxxxx', 'xxxx....xx', 'xxx.......', 'xxxxx.....', '.xxxxxxxx.', '..xxxxxxxx', '.......xxx', '.......xxx', 'xx....xxxx', 'xxxxxxxxx.', '.xxxxxxx..'],
  I: ['xxx', 'xxx', 'xxx', 'xxx', 'xxx', 'xxx', 'xxx', 'xxx', 'xxx', 'xxx', 'xxx', 'xxx'],
  L: ['xxx.....', 'xxx.....', 'xxx.....', 'xxx.....', 'xxx.....', 'xxx.....', 'xxx.....', 'xxx.....', 'xxx.....', 'xxx.....', 'xxxxxxxx', 'xxxxxxxx'],
  A: ['..xxxxxx..', '.xxxxxxxx.', 'xxxx..xxxx', 'xxx....xxx', 'xxx....xxx', 'xxx....xxx', 'xxxxxxxxxx', 'xxxxxxxxxx', 'xxx....xxx', 'xxx....xxx', 'xxx....xxx', 'xxx....xxx'],
  G: ['..xxxxxx..', '.xxxxxxxxx', 'xxxx....xx', 'xxx.......', 'xxx.......', 'xxx..xxxxx', 'xxx..xxxxx', 'xxx....xxx', 'xxx....xxx', 'xxxx...xxx', '.xxxxxxxxx', '..xxxxxxx.'],
  K: ['xxx....xxx', 'xxx...xxx.', 'xxx..xxx..', 'xxx.xxx...', 'xxxxxx....', 'xxxxx.....', 'xxxxxx....', 'xxx.xxx...', 'xxx..xxx..', 'xxx...xxx.', 'xxx....xxx', 'xxx....xxx'],
  E: ['xxxxxxxxx', 'xxxxxxxxx', 'xxx......', 'xxx......', 'xxx......', 'xxxxxxx..', 'xxxxxxx..', 'xxx......', 'xxx......', 'xxx......', 'xxxxxxxxx', 'xxxxxxxxx'],
  R: ['xxxxxxxx..', 'xxxxxxxxx.', 'xxx...xxxx', 'xxx....xxx', 'xxx...xxxx', 'xxxxxxxxx.', 'xxxxxxxx..', 'xxx..xxx..', 'xxx...xxx.', 'xxx...xxx.', 'xxx....xxx', 'xxx....xxx'],
  D: ['xxxxxxx...', 'xxxxxxxxx.', 'xxx...xxxx', 'xxx....xxx', 'xxx....xxx', 'xxx....xxx', 'xxx....xxx', 'xxx....xxx', 'xxx....xxx', 'xxx...xxxx', 'xxxxxxxxx.', 'xxxxxxx...'],
  N: ['xxxx...xxx', 'xxxxx..xxx', 'xxxxx..xxx', 'xxxxxx.xxx', 'xxx.xx.xxx', 'xxx.xxxxxx', 'xxx..xxxxx', 'xxx..xxxxx', 'xxx...xxxx', 'xxx...xxxx', 'xxx....xxx', 'xxx....xxx'],
  ' ': ['...', '...', '...', '...', '...', '...', '...', '...', '...', '...', '...', '...'],
  T: ['xxxxxxxxx', 'xxxxxxxxx', '...xxx...', '...xxx...', '...xxx...', '...xxx...', '...xxx...', '...xxx...', '...xxx...', '...xxx...', '...xxx...', '...xxx...'],
};
// Compose the word at 2x mask resolution (outer corners rounded), then shade it with a
// vertical ramp, a white top-left rim, an extruded base and a 1px outline — all native pixels.
(function logo() {
  const word = 'STAR GARDEN', gap = 3, depth = 4, K = 2;
  const widths = [...word].map(c => LOGO[c][0].length * K);
  const W = widths.reduce((a, b) => a + b, 0) + gap * (word.length - 1) + 2, H = 12 * K + depth + 2;
  const m = [];
  for (let y = 0; y < H; y++) m.push(new Array(W).fill(0));
  let x0 = 1;
  [...word].forEach((c, i) => {
    LOGO[c].forEach((row, y) => {
      for (let x = 0; x < row.length; x++) if (row[x] === 'x') for (let j = 0; j < K; j++) for (let k = 0; k < K; k++) m[y * K + j + 1][x0 + x * K + k] = 1;
    });
    x0 += widths[i] + gap;
  });
  const at = (x, y) => y >= 0 && y < H && x >= 0 && x < W && m[y][x] === 1;
  const cut = [];
  for (let y = 0; y < H; y++) for (let x = 0; x < W; x++) {
    if (!at(x, y)) continue;
    const u = at(x, y - 1), d = at(x, y + 1), l = at(x - 1, y), r = at(x + 1, y);
    if ((!u && !l) || (!u && !r) || (!d && !l) || (!d && !r)) cut.push([x, y]);
  }
  for (const [x, y] of cut) m[y][x] = 0;
  const face = at;
  const bottom = 12 * K;
  const rows = [];
  for (let y = 0; y < H; y++) {
    let r = '';
    for (let x = 0; x < W; x++) {
      if (face(x, y)) {
        const edge = !face(x, y - 1) || !face(x - 1, y);
        const f = y / bottom;
        const ramp = f < 0.3 ? 'Y' : f < 0.55 ? 'y' : f < 0.8 ? 'O' : 'o';
        r += edge && f < 0.55 ? 'w' : edge ? 'Y' : ramp;
      } else {
        let ext = 0;
        for (let d = 1; d <= depth; d++) if (face(x, y - d)) { ext = d; break; }
        r += ext ? (ext >= depth - 1 ? 'p' : 'P') : '.';
      }
    }
    rows.push(r);
  }
  def('logo', autoOutline(rows.map(r => '.' + r + '.').concat(['.'.repeat(W + 2)])));
})();
