'use strict';
// Art for the second wave of foes: four more per land. Colour pixels only, then an
// automatic '0' outline; light from the top left.
(function foes() {
  const o = { flip: true, flash: true, glow: true };
  const F = (name, art) => def(name, autoOutline(parseArt(name, art)), o);

  // ---------- Bloom Meadow ----------
  // Bunny: sits, then bounds in quick hops.
  F('bunny_0', `
    ..............
    ...L....L.....
    ...Lq...Lq....
    ...Lq...Lq....
    ...LLl..LLl...
    ..LLLLLLLLLl..
    ..LLrLLLrLLl..
    ..LLLLqqLLLl..
    ..lLLLLLLLll..
    ...lLLLLLll...
    ...lll..lll...
    ..............`);
  F('bunny_1', `
    ..............
    ....L....L....
    ....Lq...Lq...
    ...LLl..LLl...
    ..LLLLLLLLLl..
    ..LLrLLLrLLl..
    ..LLLLqqLLLl..
    ..lLLLLLLLll..
    ...lLLLLLll...
    ..ll......ll..
    .ll........ll.
    ..............`);
  // Snail: its shell stops shots from the front.
  F('snail_0', `
    ................
    .......NNNN.....
    ......NOOOONn...
    .....NOnnnnONn..
    .....NOnOONONn..
    .....NOnOnnONn..
    .c...NOnnnOONn..
    ..c...NOOOONn...
    ..hhh..nnnnn....
    .hhh0hGGGGGGGg..
    .hhhhhhhhhhhhGg.
    ..ggggggggggggg.
    ................`);
  F('snail_1', `
    ................
    .......NNNN.....
    ......NOOOONn...
    .....NOnnnnONn..
    .....NOnOONONn..
    .c...NOnOnnONn..
    ..c..NOnnnOONn..
    ..hh..NOOOONn...
    .hhhh..nnnnn....
    .hh0hhGGGGGGGGg.
    ..hhhhhhhhhhhhGg
    ...gggggggggggg.
    ................`);
  // Dandelion: rooted; puffs out drifting seeds.
  F('dandelion_0', `
    ................
    .....LwLLw......
    ...LwLLLLLLl....
    ..LLLLLLLLLLl...
    ..wLLLyyyLLLl...
    ..LLLyYyyyLLl...
    ..LLLyyyyoLLl...
    ..lLLLyyoLLll...
    ...lLLLLLLll....
    .....llll.......
    .......g........
    ...hG..g........
    ...hGG.g..Gg....
    ....GggggGg.....
    ................`);
  F('dandelion_1', `
    ................
    ..w..w....w.....
    ....LLLLL...w...
    ..LLLLLLLLl.....
    .LLLLyyyLLLl..w.
    .LLLyYyyyLLl....
    .LLLyyyyoLLl....
    .lLLLyyoLLll....
    ..lLLLLLLll.....
    ....llll........
    .......g........
    ...hG..g........
    ...hGG.g..Gg....
    ....GggggGg.....
    ................`);
  // Ladybug: flies over the hero and drops spots that linger.
  F('ladybug_0', `
    ................
    ..CC......CC....
    .CwwC....CwwC...
    ..CCC....CCC....
    ....RRRRRR......
    ...RqR1RRRr.....
    ..RRR11RR1Rr....
    ..R1RRR1RRRr....
    ..RRRRRRR1rr....
    ...rRR1Rrrr.....
    ...21rrrr12.....
    ....2....2......
    ................`);
  F('ladybug_1', `
    ................
    ................
    ................
    ...CCCCRRRCCC...
    ..CwwRRqRRRwwC..
    ...RqR1RRRrCC...
    ..RRR11RR1Rr....
    ..R1RRR1RRRr....
    ..RRRRRRR1rr....
    ...rRR1Rrrr.....
    ...21rrrr12.....
    ....2....2......
    ................`);
  // Bee Courier: a bee in a postman's cap with a satchel of letters. Wings up / down,
  // calm or cross (a frown and its stinger out).
  const COURIER = [
    '................',
    '................',
    '................',
    '........cB......',
    '.......cBBb.....',
    '.......BBBbbb...',
    '.....1Y1yy......',
    '....Y1Y1yyy.....',
    '...yY1y1yw0y....',
    '..nywLy1yyRy....',
    '...oNNNnyyyo....',
    '....NAnnyoo.....',
    '.....nnnoo......',
    '................'];
  const WING = [[1, 2, ['..wC.', '.wCCC', '.CCCc', '..Cc.']], [1, 5, ['wCC.', 'CCcc']]];
  const CROSS = [[9, 7, '0'], [1, 9, 'r'], [10, 9, 'r']];
  for (let m = 0; m < 2; m++) for (let f = 0; f < 2; f++) {
    let rows = stamp(COURIER, WING[f][0], WING[f][1], WING[f][2]);
    if (m) for (const [x, y, c] of CROSS) rows = stamp(rows, x, y, c);
    F('courier_' + (m * 2 + f), rows);
  }
  // Pollen: shaken off the courier when it is hit, heals a little.
  def('pollen', autoOutline(parseArt('pollen', `
    .......
    ..Yyy..
    .YwyyO.
    .yyyOO.
    ..OOo..
    .......`)));
  // Dandelion Puff: a floating seed clock. It swells up, then bursts into seeds.
  F('puff_0', `
    ............
    .....w.w....
    ...wLwLLl...
    ..wLLLLLLl..
    .wLLLLLLLLl.
    ..LL0LL0Ll..
    ..LqLLLLql..
    ..lLLLLLLl..
    ...llLlll...
    .....g......
    ............`);
  F('puff_1', `
    ............
    ....w...w...
    ...wLwLLl...
    .wwLLLLLLll.
    ..LLLLLLLl..
    ..LL0LL0Ll..
    ..LqLLLLql..
    ..lLLLLLLl..
    ...llLlll...
    .....g......
    ............`);
  F('puff_2', `
    ............
    ....w.w.w...
    ...wLwLLLl..
    ..wLLLLLLLl.
    .wLLLLLLLLl.
    ..LL00L00Ll.
    .lqqLLpLqql.
    ..lLLLLLLLl.
    ...llLLlll..
    ....lllll...
    ......g.....
    ............`);
  // its seeds: a white tuft on a little yellow seed (a bullet family of their own)
  const pad = (rows) => autoOutline(['.'.repeat(rows[0].length + 2)].concat(rows.map(r => '.' + r + '.'), ['.'.repeat(rows[0].length + 2)]));
  def('eb_fluff', pad(['wLw.', 'LwLl', '.Lly', '..yo']));
  def('ebb_fluff', pad(['.wLw..', 'wLwLl.', 'LwLLl.', '.lLly.', '...yyo', '....o.']));
  alias('ebcb_fluff', 'eb_fluff'); alias('ebbcb_fluff', 'ebb_fluff');

  // ---------- Sunny Shore ----------
  // Seagull: circles high, then dives along a line.
  F('gull_0', `
    ..................
    .LL............LL.
    .lLL..........LLl.
    ..lLLL......LLLl..
    ...llLLLLLLLLll...
    .....LLLLLLl......
    ....LL0LLLLlOO....
    ....LLLLLLLlo.....
    .....lLLLLll......
    ......llll........
    ..................`);
  F('gull_1', `
    ..................
    ..................
    ..................
    .....LLLLLLl......
    ....LL0LLLLlOO....
    .lLLLLLLLLLLLLLl..
    ..mllLLLLLLLllm...
    ....mm.lllll.mm...
    .......llll.......
    ..................
    ..................`);
  // Starfish: skids around like a billiard ball.
  F('starfish_0', `
    ................
    .......R........
    ......RRo.......
    ......ROo.......
    .RRRRRRRRRooo...
    ..ROOROOROOo....
    ...RR0OO0Oo.....
    ....ROOOOo......
    ...ROOoOOOo.....
    ..ROo....ROo....
    ..Ro......oo....
    ................`);
  F('starfish_1', `
    ................
    ................
    .......R........
    ......RRo.......
    ..RRRRRRRRooo...
    ...ROR0OO0oo....
    ....ROOOOOo.....
    ...ROOoOOOo.....
    ..ROo....ROo....
    .Roo......Roo...
    ................
    ................`);
  // Pufferfish: puffs up when you come close, then bursts into spikes.
  F('puffer_0', `
    ................
    ................
    ....YYYYY.......
    ...YyyyyyO......
    ..YYywyyyyO.T...
    ..Yyy0yyyyOTT...
    ..YyyyyyyyOTt...
    ..yyyRyyyoO.t...
    ...yyyyyoO......
    ....oooOO.......
    ................
    ................`);
  F('puffer_1', `
    ...y..y..y......
    .y.YYYYYYYy.....
    ..YyyyyyyyOO....
    .YYywwyyyyyOy...
    yYyyy0yyyyyO.T..
    .Yyyyyyyyyy0TT..
    yYyyyRRyyyyOTt..
    .yyyyyyyyyoO..t.
    ..yyyyyyyooO....
    .y.oooooooo.y...
    ...o..o..o......
    ................`);
  // Hermit crab: hides in its shell, then pops out with a fan of bubbles.
  F('hermit_0', `
    ................
    ......qqqq......
    .....qPPPPq.....
    ....qPpPPpPp....
    ....qPPppPPp....
    ...qPPPPPPPpp...
    ...PpPPpPPpPp...
    ...ppppppppppp..
    .RRR.R0RR0R.RRR.
    .RRr.RRRRRR.RRr.
    ..rr..r..r..rr..
    ................`);
  F('hermit_1', `
    ................
    ................
    ................
    ......qqqq......
    .....qPPPPq.....
    ....qPpPPpPp....
    ....qPPppPPp....
    ...qPPPPPPPpp...
    ...PpPPpPPpPp...
    ...ppppppppppp..
    ................
    ................`);

  // Hermit Roller: a crab in a round whelk shell; it tucks in and rolls like a marble.
  // The shell is sculpted; its spiral groove is drawn at four turns for the roll.
  const whelk = (cy, ph) => {
    let r = sculpt(20, 14, [{ e: [7.5, cy, 5.4, 5.3], ramp: 'tTTC' }]);
    const g = r.map(s => s.split(''));
    const cx = 7.5, end = (4.4 - 0.9) / 0.42;
    for (let a = 0; a <= end; a += 0.05) {
      const d = 0.9 + a * 0.42, x = Math.floor(cx + Math.cos(a + ph) * d), y = Math.floor(cy + Math.sin(a + ph) * d);
      if (g[y] && g[y][x] && g[y][x] !== '0' && g[y][x] !== '.') g[y][x] = 't';
    }
    // the opening at the end of the groove: pink inside
    const ex = cx + Math.cos(end + ph) * 3.9, ey = cy + Math.sin(end + ph) * 3.9;
    for (const [dx, dy] of [[0, 0], [1, 0], [0, 1], [-1, 0], [0, -1]]) {
      const x = Math.floor(ex + dx * 0.9), y = Math.floor(ey + dy * 0.9);
      if (g[y] && g[y][x] && g[y][x] !== '0' && g[y][x] !== '.') g[y][x] = dx || dy ? 'q' : 'P';
    }
    return g.map(l => l.join(''));
  };
  const ROLL_END = (4.4 - 0.9) / 0.42;
  for (let f = 0; f < 2; f++) {
    // walking: the opening faces front-right and the crab steps out of it
    let r = whelk(6, Math.PI / 4 - ROLL_END);
    r = stamp(r, 11, 3, [
      '..w..w..',
      '..0..0..',
      '..r..r..',
      '.RRRRR.R',
      'RRRRRRRr',
      'RRRRRrr.',
      '.rrrrr..',
      f ? '..r.r.r.' : '.r.r.r..',
    ]);
    def('roller_' + f, autoOutline(r), o);
  }
  // tucked in, then the four turns of the roll (the light stays top left)
  def('roller_tuck', whelk(7.5, Math.PI / 4 - ROLL_END), o);
  for (let f = 0; f < 4; f++) def('roller_r' + f, whelk(7.5, Math.PI / 4 - ROLL_END + f * Math.PI / 2), o);

  // Gull Bomber: a seagull in a pilot's cap with a clam in its feet; it drops the clam from
  // high up (the pink ring shows where) and the clam cracks into three shots.
  const BOMBER = [`
    ....................
    .LL.............LL..
    .lLL...........LLl..
    ..lLLL.......LLLl...
    ...llLLL...LLLll....
    .....llLLLLLll.NNN..
    ......LLLLLLL.NNNNn.
    ..LL.LLLLLLLLLLcCL..
    ...LLLLLLLLLLLLLLOO.
    ....llLLLLLLLLLlOo..
    ......lllllll.......
    ........O..O........
    .......qPPPPp.......
    .......pPpPpp.......
    ....................`, `
    ....................
    ....................
    ....................
    ....................
    ....................
    ...............NNN..
    .....LLLLLLL..NNNNn.
    ..LL.LLLLLLLLLLcCL..
    .LLLLLLLLLLLLLLLLOO.
    LLlllLLLLLLLLLlLOo..
    ll...mllllllmm.ll...
    ........O..O........
    .......qPPPPp.......
    .......pPpPpp.......
    ....................`];
  BOMBER.forEach((a, i) => {
    F('bomber_' + i, a);
    // without its clam (dropped): the feet tuck up
    F('bomber_' + (i + 2), a.split('\n').map((l, y, all) => y >= all.length - 4 && y < all.length - 1 ? l.replace(/[qPpO]/g, '.') : l).join('\n'));
  });
  // the falling clam
  F('clam', `
    ..........
    ...qqqP...
    ..qPPPPPp.
    ..PpPpPpp.
    ..pPpPpPp.
    ...ppppp..
    ..........`);

  // ---------- Crystal Cave ----------
  // Mole: burrows, then pops up next to you.
  F('mole_0', `
    ................
    .....NNNNN......
    ....NNNNNNn.....
    ...NN0NN0NNn....
    ...NNNqqNNNn....
    ...NNqPPqNNn....
    ..AANNqqNNnAA...
    ..AaNNNNNNnaA...
    ...NNNNNNNNn....
    ..mlmNNNNnmlm...
    .mlllmmmmmllm...
    ................`);
  F('mole_1', `
    ................
    ................
    ................
    ................
    ................
    ......m.l.......
    ....m.l..m......
    ...mlmllmlm.....
    ..mllmlllmlm....
    .mllllmlllllm...
    .mmmmmmmmmmmm...
    ................`);
  // Crystal spider: drops on a thread and spits webs.
  F('spider_0', `
    ................
    ..3..........3..
    ...3..4333..3...
    ....3433332.3...
    .33.3333332..33.
    ...3332w32w32...
    ..3.2222222223..
    .3...2222221..3.
    ....3.21112.3...
    ...3..3...3..3..
    ................`);
  F('spider_1', `
    ................
    ................
    .3....4333....3.
    ..3..4333332.3..
    ...333333332.3..
    .3.3332w32w323..
    ...32222222223..
    ..3..2222221.3..
    .3..3.21112..3..
    .....3.....3....
    ................`);
  // Gemlet: a small crystal golem that stomps rings of shards.
  F('gemlet_0', `
    ................
    ......CC........
    .....CwCc.......
    ....CCCCcB......
    ...lLLLLLLl.....
    ..lLLc0Lc0Lm....
    ..lLLLLLLLLm....
    ..lLLLLLLLmm....
    .CclLLLLLLmBb...
    .cB.llmmmm.bB...
    ....lm..lm......
    ....mm..mm......
    ................`);
  F('gemlet_1', `
    ................
    ................
    ......CC........
    .....CwCc.......
    ....CCCCcB......
    ...lLLLLLLl.....
    .ClLLc0Lc0LmB...
    CclLLLLLLLLmBb..
    c.lLLLLLLLmm.b..
    ...llLLLLmm.....
    ...lm....lm.....
    ..mmm....mmm....
    ................`);
  // Glow moth: flutters about and leaves clouds of glowing dust.
  F('gmoth_0', `
    ..................
    .44.....3.....44..
    .4w4.....3...4w4..
    .44344..yy..44343.
    ..4w334yYyy43w43..
    ...4334yyyo4333...
    ..43334yyyo43333..
    ..4333.yyoo.3332..
    ...33...yo...32...
    ..................`);
  F('gmoth_1', `
    ..................
    ........3.........
    .........3........
    ....44..yy..443...
    ..44w44yYyy44w43..
    .4w33344yyo433332.
    ..44333yyyo333322.
    ....44.yyoo.322...
    ........yo........
    ..................`);
  // Shard Sprite: a crystal imp that throws the tip of its own head. The tip glows white while
  // it aims, and is gone for a moment after the throw.
  const SHARD = [`
    ..............
    ......C.......
    .....CwB......
    .....Cwcb.....
    .3..CwccBb..3.
    .43.CcccBb.34.
    .443cccccB344.
    ..4cc0cc0Bb4..
    ...ccccccBb...
    ....cBBBBb....
    .....BBbb.....
    ......bb......
    ..............`, `
    ..............
    ......C.......
    .....CwB......
    .....Cwcb.....
    ....CwccBb....
    ....CcccBb....
    ...4cccccB4...
    ..44c0cc0B44..
    .443ccccccB34.
    .43..cBBBb..3.
    .3...BBbb.....
    ......bb......
    ..............`];
  SHARD.forEach((a, i) => F('imp_' + i, a));
  // aiming: the tip glows; thrown: the tip is gone (the head is flat on top)
  const tip = (rows) => stamp(parseArt('imp', SHARD[0]), 5, 1, rows);
  def('imp_2', autoOutline(tip(['.w..', 'wwY.', 'CwwC'])), o);
  def('imp_3', autoOutline(tip(['._..', '___.', 'CCCC'])), o);
  // Geode Beetle: rolls about shut like a plain stone (shots bounce off), then cracks open to
  // shoot. Open, it glows purple: harmless to touch, and soft.
  const GSEAM = x => 7 - (x % 4 === 1 ? 1 : 0);
  const geode = (f, seam) => {
    let r = sculpt(16, 14, [{ e: [7.5, 6.5, 6.6, 5.6], ramp: 'dmlL' }]);
    // a zigzag seam between the halves, and two amethyst specks that turn with the roll
    r = r.map((l, y) => l.replace(/[dmlL]/g, (c, x) => x > 1 && x < 14 && y === GSEAM(x) ? (seam ? (x % 2 ? 'w' : '4') : '2') : c));
    const sp = [[4, 3], [9, 3], [10, 8], [4, 8]];
    for (const k of [0, 2]) { const [x, y] = sp[(k + f) % 4]; r = stamp(r, x, y, seam ? ['4w', '34'] : ['34', '23']); }
    // little legs scuttling under the shell
    const lx = f % 2 ? [4, 7, 10] : [5, 8, 11];
    for (const x of lx) r = stamp(r, x, 12, 'm');
    return autoOutline(r);
  };
  for (let f = 0; f < 4; f++) def('gbeet_' + f, geode(f), o);
  // cracking: the seam and the specks glow
  def('gbeet_tell', geode(0, true), o);

  // ---------- Cloud Steps ----------
  // Puff Sheep: a ball of wool that bounces at you; hit it and it pops into two lambs.
  const wool = (w, h, lumps, head, legs) => {
    let r = sculpt(w, h, lumps.map(e => ({ e, ramp: 'lLww', noLine: true })).concat([{ e: head, ramp: 'dmml', hi: false }]));
    const [hx, hy] = head;
    r = stamp(r, Math.round(hx + 0.4) - 1, Math.round(hy) - 1, '0'); // the eye
    r = stamp(r, Math.round(hx) - 2, Math.round(hy) - 2, 'd');  // the ear
    return autoOutline(stamp(r, 0, h - 3, legs));
  };
  const SHEEP = [[8, 7.5, 6.4, 4.2], [4.5, 5.5, 2.8, 2.4], [8.5, 4, 3, 2.3], [12, 5.5, 2.4, 2], [4.5, 9.5, 2.6, 1.8]];
  def('sheep_0', wool(18, 14, SHEEP, [14.6, 8.2, 2.4, 2.8], ['...m..m...m..m....', '...d..d...d..d....']), o);
  def('sheep_1', wool(18, 14, SHEEP, [14.6, 7.6, 2.4, 2.8], ['..................']), o);
  const LAMB = [[5.5, 6.5, 4.4, 3], [4, 4.5, 2.2, 1.8], [7, 4.2, 2, 1.6]];
  def('lamb_0', wool(13, 13, LAMB, [10.2, 6.8, 2, 2.3], ['...m..m.m....', '...d..d.d....']), o);
  def('lamb_1', wool(13, 13, LAMB, [10.2, 6.2, 2, 2.3], ['.............']), o);

  // Kite Ray: a manta-shaped kite that glides on the wind and drops water balloons.
  F('kiteray_0', `
    ....................
    .........cc.........
    .......cBBBBb.......
    .....cBBBBBBBBb.....
    ...cBBB0BBBB0BBBb...
    .cBBBBBBBBBBBBBBBBb.
    ..bbBBBBBqqBBBBBbb..
    ....bbBBBBBBBBbb....
    ......bbBBBBbb......
    ........bBBb........
    .........bb.........
    ..........P.........
    .........P..........
    ..........q.........`);
  F('kiteray_1', `
    ....................
    .........cc.........
    .......cBBBBb.......
    .....cBBBBBBBBb.....
    ....cBB0BBBB0BBb....
    ...cBBBBBBBBBBBBb...
    .cBBBBBBBqqBBBBBBBb.
    ..bb..bBBBBBBb..bb..
    ......bbBBBBbb......
    ........bBBb........
    .........bb.........
    .........P..........
    ..........P.........
    .........q..........`);
  F('kite_bomb', `
    .........
    ....P....
    ...cBb...
    ..cCBBb..
    ..cBBBb..
    ..BBBbb..
    ...bbb...
    .........`);

  // Storm Wisp: a small grumpy thundercloud. It crackles, then calls down a bolt.
  const storm = (f) => {
    let r = sculpt(16, 13, [
      { e: [8, 6.5, 6.4, 3.4], ramp: 'dmlL', noLine: true }, { e: [5, 4.5, 3, 2.6], ramp: 'dmlL', noLine: true },
      { e: [9.5, 3.5, 3, 2.6], ramp: 'dmlL', noLine: true }, { e: [12.5, 5.5, 2.4, 2.2], ramp: 'dmlL', noLine: true }]);
    r = stamp(r, 5, 6, f === 2 ? '0...0' : '0..0.');
    r = stamp(r, 6, 8, f === 2 ? '.00.' : '.qq.');
    // a little bolt dangling underneath, bright while it charges
    return autoOutline(stamp(r, 6, 10, f === 2 ? ['.wY', 'wY.', '.Y.'] : f ? ['..y', '.y.', '..y'] : ['.y.', 'y..', '.y.']));
  };
  for (let f = 0; f < 3; f++) def('stormwisp_' + f, storm(f), o);

  // Pigeon Postman: a pigeon in a mail cap; its letter flies out and comes back.
  const PIGEON = `
    ................
    ........bbb.....
    .......bbyBb....
    ........lLLl....
    ........L0LlO...
    ........TTLlOo..
    ..lLLLLLTtl.....
    .lLLLLLLLLl.....
    .mlllLLLLlm.....
    ..mmNNnllmm.....
    ....mnnmm.......
    .....O..O.......
    ................`;
  F('pigeon_0', stamp(parseArt('pigeon_0', PIGEON), 2, 3, ['.lLL', 'lLLl', 'Llm.']).join('\n'));
  F('pigeon_1', stamp(parseArt('pigeon_1', PIGEON), 1, 7, ['.....', 'llLL.', 'mmlll', '.mm..']).join('\n'));
  F('pigeon_2', stamp(parseArt('pigeon_2', PIGEON), 2, 3, ['.lLL', 'lLLl', 'Llm.']).join('\n').replace('L0L', 'LwL'));
  const pad2 = (rows) => autoOutline(['.'.repeat(rows[0].length + 2)].concat(rows.map(r => '.' + r + '.'), ['.'.repeat(rows[0].length + 2)]));
  def('eb_letter', pad2(['wLLl', 'LPql', 'lllm']));
  def('ebb_letter', pad2(['wLLLLl', 'LwLLlm', 'LLPplm', 'lllmmm']));
  alias('ebcb_letter', 'eb_letter'); alias('ebbcb_letter', 'ebb_letter');

  // Nimbus Knight: cloud armour and a sun shield held in front; it stomps the clouds away.
  const KNIGHT = `
    ..................
    .......PP.........
    ......PqP.........
    .....lLLLl........
    ....lLLLLLl.......
    ....lL0LL0l.......
    ....llLLLlm.......
    ...BBlmmmdB.......
    ..cBBBBBBBBB......
    ..cBBBwBBBBb......
    ..BBBBBBBBBb......
    ...bBBBBBBb.......
    ....ll..ll........
    ....mm..mm........
    ..................`;
  const SHIELD = ['.YY..', 'YyYyo', 'yYOyo', 'yyOoo', 'yyyoo', '.ooo.'];
  const knight = (legs, shield, sy) => {
    let r = stamp(parseArt('nimbus', KNIGHT), 0, 12, legs);
    if (shield) r = stamp(r, 11, sy, SHIELD);
    return autoOutline(r);
  };
  def('nimbus_0', knight(['....ll..ll........', '....mm..mm........'], true, 6), o);
  def('nimbus_1', knight(['...ll....ll.......', '...mm....mm.......'], true, 6), o);
  // the stomp: one foot up (the tell), then down hard, shield at its side
  def('nimbus_2', knight(['....ll....ll......', '....mm............'], true, 8), o);
  def('nimbus_3', knight(['...ll.....ll......', '...mm.....mm......'], false, 0), o);

  // Balloon Bandit: a masked raccoon hanging from three balloons, after your coins.
  const BANDIT = `
    .................
    ..qP....Yy.......
    .qPPp..YyyO......
    .PPpp..yyOo..cC..
    ..pp....oo..cCBb.
    ...l....l...cBbb.
    ....l...l....bb..
    .....l..l...l....
    ......l.l.l......
    .......lll.......
    .....nN...Nn.....
    .....NNNNNNN.....
    .....xwxAxwx.....
    .....NAA0AAN.....
    ......NNyNN......
    .....nNNNNNn.....
    ......n...n......
    .................`;
  F('bandit_0', BANDIT);
  F('bandit_1', BANDIT.replace('......n...n......', '.......n.n.......'));
})();

// ---------- Lantern Woods ----------
(function lanternFoes() {
  const o = { flip: true, flash: true, glow: true };
  const F = (name, art) => def(name, autoOutline(typeof art === 'string' ? parseArt(name, art) : art), o);
  // a symmetric sprite from its left half plus the middle column; the right half is the
  // mirror, one step darker (light from the top left)
  const sym = (rows, map) => rows.map(([l, c]) => l + c + [...l].reverse().map(ch => map[ch] || ch).join(''));

  // Wisp Fox: a little fox with a will-o'-the-wisp for a tail. It sneaks up for your coins.
  const FOX = [
    '..................',
    '..C........y...y..',
    '.cwC.......On.On..',
    '.cCc......yOOOOOo.',
    '..cC......O0OOO0o.',
    '..cB......AAA0AAo.',
    '..Bc.yOOOOoAAAAo..',
    '...BOOOOOOOoAAo...',
    '....oOAAAAAOoo....',
    '....nooAAAoon.....',
    '....n.n...n.n.....',
    '..................'];
  const fox = (f, coin) => {
    let r = FOX.slice();
    if (f) r[10] = '.....n.n.n.n......';
    if (f) r = stamp(r, 1, 1, ['.C.', 'cw.', 'Cc.']); // the flame flickers
    if (coin) r = stamp(r, 14, 6, ['Yy', 'yo']); // a stolen coin in its mouth
    return r;
  };
  F('wfox_0', fox(0)); F('wfox_1', fox(1));
  F('wfox_c0', fox(0, 1)); F('wfox_c1', fox(1, 1));

  // Stump Sentry: an old stump that wakes when a lamp lights near it.
  const stump = (awake, aim) => {
    let r = sculpt(20, 19, [
      { r: [1, 14, 18, 4, 1.5], ramp: 'unNN', hi: false },
      { r: [4, 4, 12, 13, 2], ramp: 'unNa' },
      { e: [10, 5, 6, 2.6], ramp: 'eaAA' },
    ]);
    r = stamp(r, 7, 4, ['.eee.', 'e.a.e', '.eee.']); // the rings
    r = stamp(r, 10, 0, ['.hH', 'Gh.', 'G..']); // a sprout
    r = stamp(r, 5, 8, ['u.', 'u.', '.u']); r = stamp(r, 14, 12, ['u', 'u']); // bark cracks
    r = stamp(r, 7, 9, awake ? 'YY..YY\nY0..Y0' : '......\nuu..uu');
    r = stamp(r, 9, 12, aim ? '00\n00' : awake ? 'uu' : '.u');
    return rim(r, { N: 'n', a: 'N' });
  };
  F('stump_0', stump(0)); F('stump_1', stump(1)); F('stump_2', stump(1, 1));

  // Lamp Moth: drawn to the lamps, it douses them with its wings.
  const MOTH = { L: '4', 4: '3', 3: '2', A: 'a', l: 'm' };
  F('lmoth_0', sym([
    ['........', '.'], ['.LL4...4', '.'], ['.L4O44.l', '.'], ['.4OyO43A', 'A'], ['.44O432a', 'A'],
    ['..4432.a', 'A'], ['...L43.a', 'a'], ['..L43..a', 'a'], ['..443...', 'a'], ['...3....', '.'],
    ['........', '.'], ['........', '.']], MOTH));
  F('lmoth_1', sym([
    ['........', '.'], ['.......4', '.'], ['......l.', '.'], ['.......A', 'A'], ['.LL44..a', 'A'],
    ['.4LO443a', 'A'], ['.4OyO43a', 'a'], ['.44O432a', 'a'], ['..L443..', 'a'], ['..443...', '.'],
    ['...3....', '.'], ['........', '.']], MOTH));

  // Hollow Owlet: sleeps on a lamp post and swoops when the lamp is lit.
  const OWL = { a: 'N', N: 'n', n: 'u', A: 'a' };
  const owl = (eyes, wings) => sym([
    ['.........', '.'], ['...N.....', '.'], ['...NN....', '.'], ['...nNaNNN', 'N'], ['...nAAAAe', 'n'],
    ['...nA' + eyes[0] + 'Ae', 'n'], ['...nA' + eyes[1] + 'Ae', 'O'], ['...nAAAAe', 'o'],
    [wings[0] + '.unNaNN', 'N'], [wings[1] + '.unaANN', 'N'], [wings[2] + '.unNANN', 'N'], [wings[3] + '..unNNN', 'N'],
    ['.....uO.O', '.'], ['.........', '.']], OWL);
  const FOLD = ['..', '..', '..', '..'], SPREAD = ['aN', 'Nn', 'nu', 'u.'];
  F('owlet_0', owl(['YY', 'Y0'], FOLD));
  F('owlet_1', owl(['AA', 'uu'], FOLD)); // asleep
  F('owlet_2', owl(['YY', 'Y0'], SPREAD)); // the swoop

  // Mushroom Mime: stands among the lamps pretending to be one. Found out, it puffs spores.
  const CAP = ['.....qqqq.....', '...qqwqqPP....', '..qqwwqPPPP...', '..qPPPPPPwPP..', '.qPPwPPPPPPPp.', '.PPPPPPPPPPPp.', '.pPPPPPPPwPpp.', '..pppppppppp..'];
  const mime = (puff) => ['..............', '..............'].slice(puff).concat(CAP, [
    '...wwwwwwLl...',
    puff ? '...wwuwwuLl...' : '...ww0ww0Ll...',
    puff ? '...wwq00qLl...' : '...wwqrrqLl...',
    puff ? '...www00wLl...' : '...wwwwwwLl...',
  ], puff ? ['...wwwwwwLl...'] : [], ['...xLxLxLxl...', '...LxLxLxLl...', '....llllll....', '..............']);
  F('mime_0', mime(0)); F('mime_1', mime(1));

  // Pumpkin Hopper: a carved pumpkin with a candle inside. Where it lands, the ground burns.
  const pumpkin = (hop) => {
    let r = sculpt(18, 17, [
      { r: [8, 0, 3, 5, 1], ramp: 'gGGh', hi: false },
      { e: [9, hop ? 9.5 : 10.5, hop ? 7.4 : 8, hop ? 6.8 : 6], ramp: 'noOy' },
    ]);
    const y0 = hop ? 3 : 5;
    r = stamp(r, 11, 1, ['hH', '.h']); // a leaf
    for (const x of [5, 12]) for (let y = y0 + 2; y < y0 + 10; y++) if (r[y][x] !== '0') r = stamp(r, x, y, 'o');
    r = stamp(r, 4, y0 + 3, ['.y...y.', 'yYy.yYy']);
    r = stamp(r, 4, y0 + 7, ['yYyYyYy'.slice(0, 7), 'n.y.y.n'.replace(/n/g, '.')]);
    return r;
  };
  F('phop_0', pumpkin(0)); F('phop_1', pumpkin(1));

  // the flames a Pumpkin Hopper leaves (and the Scarecrow's sweep sets)
  const FL = ['.............', '......y......', '.....yy......', '..y..yYy.....', '..yy.yYy...y.', '.yYy.yYYy..y.', '.yYyyYwYy.yO.', '.oyYyYwwYyYO.', '.oOyYYwYYyOo.', '..oOOyYyOOo..', '...ooOOOoo...', '.............'];
  const FL1 = ['.............', '.............', '.......y.....', '...y..yy.....', '..yy..yYy..y.', '..yYy.yYy.yy.', '.yYyyyYYy.yO.'].concat(FL.slice(7));
  def('flame_0', autoOutline(FL));
  def('flame_1', autoOutline(FL1));

  // bullets: acorns (Stump Sentry), spores (Mushroom Mime), embers (the Scarecrow)
  const pad = (rows) => autoOutline(['.'.repeat(rows[0].length + 2)].concat(rows.map(r => '.' + r + '.'), ['.'.repeat(rows[0].length + 2)]));
  const B = {
    acorn: [['.uu.', 'uNNn', 'oOOn', '.On.'], ['..u...', '.uNNu.', 'uNNNNn', '.OyOn.', '.OOon.', '..on..']],
    spore: [['.q.q', 'qPwP', '.PPp', 'p.p.'], ['..q.q.', '.qPqP.', 'qPwwPp', '.PwPPp', '.pPpp.', 'p..p..']],
    ember: [['.Ry.', 'RyYo', 'royo', '.or.'], ['..Ry..', '.RyYo.', 'RyYYyo', 'ryYyoo', '.royo.', '..rr..']],
  };
  for (const k in B) {
    def('eb_' + k, pad(B[k][0])); def('ebb_' + k, pad(B[k][1]));
    alias('ebcb_' + k, 'eb_' + k); alias('ebbcb_' + k, 'ebb_' + k);
  }
})();
