'use strict';
// Art for the walkable Garden: its stations, the upgrade plants (four growth stages) and the
// seed plots. Colour pixels only, then an automatic '0' outline; light from the top left.
(function gardenArt() {
  const A = (name, art, opts) => def(name, autoOutline(parseArt(name, art)), opts);

  // Mailbox on a post
  A('g_mailbox', `
    ..............
    ....RRRRRR....
    ...RRqRRRRr...
    ...RqwRRRRr.y.
    ...RRRRRRRr.y.
    ...RRRRRRrr.o.
    ...rrrrrrrr...
    ......Nn......
    ......Nn......
    ......Nn......
    ......Nn......
    .....NNnn.....
    ..............`);
  // Telescope on three legs
  A('g_scope', `
    ................
    ...........CC...
    .........BBCw...
    .......BBBBcC...
    .....BBBBBb.....
    ...cBBBBbb......
    ...BBbbb........
    ....bb..........
    .....Nn.........
    ....N.n.N.......
    ...N..n..N......
    ..N...n...N.....
    ................`);
  // Bookshelf
  A('g_shelf', `
    ..................
    .NNNNNNNNNNNNNNNn.
    .NrrBBhhyyPPccrNn.
    .NrrBBhhyyPPccrNn.
    .NrrBBhhyyPPccrNn.
    .NnnnnnnnnnnnnnNn.
    .NcPPyyrrBBhhccNn.
    .NcPPyyrrBBhhccNn.
    .NcPPyyrrBBhhccNn.
    .NnnnnnnnnnnnnnNn.
    .NNNNNNNNNNNNNNNn.
    .nn............nn.
    ..................`);
  // Wardrobe (a tall cupboard with a star)
  A('g_wardrobe', `
    ..............
    ..NNNNNNNNNN..
    ..NOOOOOOOOn..
    ..NONNNnNNOn..
    ..NON.YnNNOn..
    ..NONYYYNNOn..
    ..NON.Yn.NOn..
    ..NONNNnNNOn..
    ..NONNNnNNOn..
    ..NONNyny.On..
    ..NONNNnNNOn..
    ..NOOOOOOOOn..
    ..nnnnnnnnnn..
    ..n........n..
    ..............`);
  // Wand rack with three wands
  A('g_rack', `
    ................
    ...Y....c....P..
    ..YwY..CwC..PqP.
    ...N....N....N..
    ...N....N....N..
    .NNNNNNNNNNNNNN.
    .nnnnnnnnnnnnnn.
    ...N........N...
    ...N........N...
    ..nn........nn..
    ................`);
  // Quest board with pinned notes
  A('g_board', `
    ..................
    .NNNNNNNNNNNNNNNn.
    .NAAAa.AAAa.Aaa.n.
    .NAeea.Aeea.Aea.n.
    .NAAAa.AAAa.AAa.n.
    .N.....r....y...n.
    .N.AAAa..AAAAa..n.
    .N.Aeea..Aeeea..n.
    .N.AAAa..AAAAa..n.
    .NNNNNNNNNNNNNNNn.
    ....Nn......Nn....
    ....Nn......Nn....
    ...NNnn....NNnn...
    ..................`);
  // The frog's stall: an awning over a counter
  A('g_stall', `
    ..............................
    .RRwwRRwwRRwwRRwwRRwwRRwwRRww.
    .RRwwRRwwRRwwRRwwRRwwRRwwRRww.
    ..rr..rr..rr..rr..rr..rr..rr..
    ..N........................N..
    ..N........................N..
    ..N........................N..
    ..N........................N..
    .NNNNNNNNNNNNNNNNNNNNNNNNNNNn.
    .NOOOOOOOOOOOOOOOOOOOOOOOOONn.
    .NnnnnnnnnnnnnnnnnnnnnnnnnnNn.
    .Nn........................Nn.
    .nn........................nn.
    ..............................`);
  // A seed plot: tilled soil
  A('g_plot', `
    ....................
    ..nNNNNNNNNNNNNNNn..
    .nNnNnNnNnNnNnNnNNn.
    .nnNnNnNnNnNnNnNnNn.
    .nNnNnNnNnNnNnNnNNn.
    ..nnnnnnnnnnnnnnnn..
    ....................`);
  // What grows on a plot: a sprout, a bud, a star flower (glowing when ripe)
  A('g_sprout_0', `
    ........
    ...h....
    ..hGh...
    ...g....
    ...g....
    ........`);
  A('g_sprout_1', `
    ..........
    ...hh.....
    ..hGGg.hh.
    ...gg.hGg.
    ....g.gg..
    ....gg....
    .....g....
    ..........`);
  A('g_sprout_2', `
    ..........
    ....Y.....
    ...YwY....
    ..hhY.....
    ..hGGg.hh.
    ...gg.hGg.
    ....g.gg..
    ....gg....
    .....g....
    ..........`);
  // Upgrade plants: four stages; the flower takes the upgrade's colour (legend on 'P')
  const PLANT = [
    `
    ........
    ........
    ........
    ...h....
    ..hGh...
    ...g....
    ...g....
    ........`, `
    ..........
    ..........
    ...hh.....
    ..hGGg.hh.
    ...gg.hGg.
    ..h.g.gg..
    .hGggg....
    ..gg.g....
    .....g....
    ..........`, `
    ............
    .....PP.....
    ....PqPp....
    ....PPpp....
    ..hh.pp.hh..
    .hGGg.g.hGg.
    ..ggg.ghGg..
    ...hGggg....
    ....gg.g....
    .......g....
    ............`, `
    ..............
    ..PP......PP..
    .PqPp.PP.PqPp.
    .PPpp.qP.PPpp.
    ..pp.PPpp.pp..
    ..g.hPPp..g...
    .hGg.pp.hGg...
    ..gghgg.gg.hh.
    ...hGg.g..hGg.
    ....ggggggg...
    ......gg......
    .......g......
    ..............`];
  const FLOWER = { P: ['P', 'q', 'p'], R: ['R', 'Y', 'r'], y: ['y', 'Y', 'o'], c: ['c', 'C', 'B'], '3': ['3', '4', '2'], h: ['h', 'H', 'g'], O: ['O', 'Y', 'o'] };
  for (const k in FLOWER) {
    const [P, q, p] = FLOWER[k];
    PLANT.forEach((art, i) => A('g_plant' + i + '_' + k, art, { legend: { P, q, p } }));
  }
})();
