'use strict';
// Icons for the second batch of magic items, the charms, star scrolls, door reward marks
// and the nemesis crown. Colour pixels only; autoOutline adds the '0' outline. Light from
// the top left: highlights on top-left edges, shade on the bottom right.

(function itemIcons() {
  const I = (name, art) => def('icon_' + name, autoOutline(parseArt('icon_' + name, art)), { sil: '1' });

  I('glass', `
    ................
    .......CC.......
    ......CwwC......
    ......CwCc......
    .CCCCCwCcccccc..
    ..CwwwwCwwwwc...
    ...Cww1ww1wc....
    ....Cw1ww1c.....
    ....CwwwCwc.....
    ...CwwwCwwwc....
    ...CwwcccCwc....
    ..Cwwc....cCwc..
    ..Cwc......ccc..
    ..cc........cc..
    ................
    ................`);
  I('crown', `
    ................
    ................
    ..Y....Y....Y...
    ..YY..YyY..Yy...
    ..YyY.YyY.Yyy...
    ..YyyYyyyYyyy...
    ..YyyyyyyyyyyO..
    ..YyrRyyyBcyyo..
    ..YyrryyyBByyo..
    ..Yyyyyyyyyyyo..
    ..oooooooooooo..
    ................
    ................
    ................
    ................
    ................`);
  I('nectar', `
    ................
    ......NNN.......
    ......nnn.......
    .....LLLLL......
    ....LlLLLLl.....
    ....LOOOOOl.....
    ...LOYyyyyOl....
    ...LOYyyyyol....
    ...LOyyyyyol....
    ...LOyyyyool....
    ...LlOoooool....
    ....llllllll....
    ................
    ................
    ................
    ................`);
  I('crescent', `
    ................
    .....YYYY.......
    ...YYyy.........
    ..YYy...........
    ..Yy............
    .YYy............
    .Yyy............
    .Yyy............
    .Yyy............
    .yyyy...........
    ..yyyo........o.
    ..oyyyo.....ooo.
    ...ooyyyooooo...
    .....ooooooo....
    ................
    ................`);
  I('moonstone', `
    ................
    ................
    ......4444......
    ....44433332....
    ...4w4333332....
    ...4w433332222..
    ..43443332222...
    ..4333332222212.
    ..3333322221112.
    ...33222211112..
    ...2222111112...
    ....22111112....
    .....222222.....
    ................
    ................
    ................`);
  I('beehat', `
    ................
    ....C....C......
    ...CwC..CwC.....
    ...CCC..CCC.....
    .....YYYYY......
    ....YYyyyyy.....
    ...Yy1yy1yyy....
    ...Yy1yy1yyy....
    ..YYyyyyyyyyy...
    ..Yyyyyyyyyyyo..
    .oooooooooooooo.
    ..nnnnnnnnnnnn..
    ................
    ................
    ................
    ................`);
  I('stinger', `
    ................
    ................
    ..........Yy....
    .........Yyy....
    ........Yyy1....
    .......Yyy1.....
    ......Yy11......
    .....ly11.......
    ....lL1.........
    ...lL...........
    ..lL............
    .ll.............
    .d..............
    ................
    ................
    ................`);
  I('royal', `
    ................
    ......llll......
    .....lLLLLl.....
    ......mmmm......
    .....LLLLLL.....
    ....LqqqqqqL....
    ....LqwqPPPl....
    ....LqwPPPPl....
    ....LqPPPPPl....
    ....LPPPPPpl....
    ....LPPPPppl....
    .....lllllll....
    ................
    ................
    ................
    ................`);
  I('meteor', `
    ................
    ................
    ....RRRRR.......
    ....RqqRr.......
    ....RqRRr.......
    ....RRRRr.......
    ....RRRRrOO.....
    ...RRRRRRRrO....
    ..RRRRRRRRRr....
    ..rrrrrrrrrr....
    ..nnnnnnnnnn..Oy
    ...........OyY..
    .........OyY....
    ................
    ................
    ................`);
  I('mirror', `
    ................
    .....NNNNNN.....
    ....NCCCCCCn....
    ...NCwwCCCCcn...
    ...NCwCCCCCcn...
    ...NCCCCCCccn...
    ...NCCCCCcccn...
    ...NCCCCccccn...
    ....NcccccccN...
    .....nnnnnnn....
    .......Nn.......
    .......Nn.......
    ......NNnn......
    ................
    ................
    ................`);
  I('watch', `
    ................
    .......yy.......
    ......yooy......
    .....YYYYYY.....
    ....YLLLLLLy....
    ...YLLLL1LLLy...
    ...YLLLL1LLly...
    ...YLLLL11lly...
    ...YLLLLLlllo...
    ...YLLLLllllo...
    ....yllllllo....
    .....oooooo.....
    ................
    ................
    ................
    ................`);
  I('feather', `
    ................
    ..........CCw...
    .........CwwC...
    ........CwwCc...
    .......CwwCc....
    ......CwwCc.....
    .....CwwCc......
    ....CwCCc.......
    ....CCcc........
    ...lCc..........
    ..l.............
    .l..............
    ................
    ................
    ................
    ................`);
  I('lens', `
    ................
    ....llllll......
    ...lCCCCCCm.....
    ..lCwwCCCCcm....
    ..lCwCCCCCcm....
    ..lCCCCCCccm....
    ..lCCCCCcccm....
    ...mcccccccm....
    ....mmmmmmmNN...
    ...........NNn..
    ............Nnn.
    .............nn.
    ................
    ................
    ................
    ................`);
  I('snow', `
    ................
    .......w........
    .....w.C.w......
    ......wCw.......
    ...w...C...w....
    ....C..C..C.....
    .....CwCwC......
    ..wCCCCwCCCCw...
    .....CwCwC......
    ....C..C..C.....
    ...w...C...w....
    ......wCw.......
    .....w.C.w......
    .......w........
    ................
    ................`);
  I('ember', `
    ................
    .......Y........
    ......YY........
    .....YyY...Y....
    .....Yyy..Yy....
    ....YyyyyYyy....
    ....YyOyyyyO....
    ...YyOOyyyOOo...
    ...YyOrOyOrOo...
    ...yOOrrOrrOo...
    ...oOrrrrrrOo...
    ....oorrrroo....
    .....ooooo......
    ................
    ................
    ................`);
  I('sprout2', `
    ................
    ................
    .....hh..hh.....
    ....hHGg.HGg....
    ....GGgggGgg....
    .....ggg.gg.....
    .......gg.......
    .......g........
    ....YYYYYYYy....
    ...YYyyyyyyyo...
    ...Yyyy0yyyyo...
    ...yyyyyyyyyo...
    ....ooooooooo...
    ................
    ................
    ................`);
  I('purse', `
    ................
    ......NNN.......
    .....NnnnN......
    ......nn........
    ....NNNNNNN.....
    ...NNNNNNNNn....
    ..NNNyYNNNNNn...
    ..NNyYYyNNNNn...
    ..NNNyyNNNNnn...
    ..NNNNNNNNnnn...
    ...nnnnnnnnn....
    ................
    ................
    ................
    ................
    ................`);
  I('dice', `
    ................
    ................
    ...LLLLLLLLL....
    ..LLLLLLLLLLl...
    ..LLrLLLLLrLl...
    ..LLLLLLLLLLl...
    ..LLLLLrLLLLl...
    ..LLLLLLLLLLl...
    ..LLrLLLLLrLl...
    ..LLLLLLLLLll...
    ..lLLLLLLLlll...
    ...llllllllm....
    ................
    ................
    ................
    ................`);
  I('prism', `
    ................
    .......4........
    ......4w3.......
    ......4w3.......
    .....4ww33......
    .....4w333......
    ....4ww3332.....
    ....4w33332.....
    ...4ww333322....
    ...4w3333322..r.
    ..4ww33333222.y.
    ..222222222222c.
    ..............3.
    ................
    ................
    ................`);
  I('thorn', `
    ................
    ......G.........
    ....G.hG..G.....
    .....hGGgGg.....
    ...GhG...gGg....
    ..G.G.....G.....
    ....h.....g.G...
    ..GhG.....gG....
    .....G...Gg.....
    ....GhGgGgg.G...
    .....G..gG......
    ........g.......
    ................
    ................
    ................
    ................`);
  I('phoenix', `
    ................
    ..........YY....
    .........YyyO...
    ........YyyO....
    .......YyOOr....
    ......YyOOr.....
    .....YyOOr......
    ....YyOOrr......
    ...yyOOrr.......
    ...yOOrr........
    ..yOrr..........
    ..yr............
    .r..............
    ................
    ................
    ................`);
  I('starmap', `
    ................
    ................
    ..AAAAAAAAAAAA..
    ..AaaaaaaaaaYe..
    ..AaYaaaaaaaae..
    ..AaaeaaaaYaae..
    ..AaaaeeaeaaaAe.
    ..AaaaaaYaaaae..
    ..AaaaaaaeaaYe..
    ..AaYaaaaaeaae..
    ..Aaaeeeeeaaae..
    ..eeeeeeeeeeee..
    ................
    ................
    ................
    ................`);
  I('wishbone', `
    ................
    ................
    ...AA......AA...
    ...Aa......ae...
    ....Aa....ae....
    .....Aa..ae.....
    ......Aaae......
    .......Ae.......
    .......Ae.......
    .......Ae.......
    .......ae.......
    ......Aaee......
    ................
    ................
    ................
    ................`);
  I('rocket', `
    ................
    ................
    ..........LLr...
    .........LLLr...
    ........LLlrR...
    .......LLlrRr...
    ......LLlrRr....
    ....rRLlrRr.....
    ....RRllRr......
    .....RlRr.......
    ....OyyR........
    ...OyYy.........
    ...yyO..........
    ...O............
    ................
    ................`);
  I('split', `
    ................
    ..........Yw....
    .........YYy....
    ........Yy......
    ...Yw..Yy.......
    ..YYyYYy........
    ..YyyYy.........
    ...yyYy.........
    ........Yy......
    .........YYy....
    ..........Yy....
    ................
    ................
    ................
    ................
    ................`);
  I('aura', `
    ................
    .....Y.Y.Y......
    ................
    ...Y...YY...Y...
    .......Yy.......
    ..Y..YYYyyo..Y..
    ......Yyyo......
    ......Yooy......
    ..Y..yo..oy..Y..
    ................
    ...Y........Y...
    .....Y.Y.Y......
    ................
    ................
    ................
    ................`);
  I('bell', `
    ................
    .......oo.......
    ......YyyO......
    .....YYyyyo.....
    .....Yyyyyo.....
    ....YYyyyyyo....
    ....Yyyyyyyo....
    ....Yyyyyyyo....
    ...YYyyyyyyyo...
    ...Yyyyyyyyyo...
    ..oooooooooooo..
    .......yo.......
    ................
    ................
    ................
    ................`);
  I('horseshoe', `
    ................
    ................
    ....LLL..LLL....
    ...LLlm..mLLm...
    ...Llm....Llm...
    ..LLm......Llm..
    ..Llm......Llm..
    ..Llm......Llm..
    ..Llm......Llm..
    ...Llm....Llm...
    ...Llmm..mmlm...
    ....mmm..mmm....
    ................
    ................
    ................
    ................`);
  I('heartstone', `
    ................
    ................
    ....qq...qq.....
    ...qwqP.qqPp....
    ..qwqPPPqPPPp...
    ..qqPPPPPPPPp...
    ..qPPPPPPPPpp...
    ...PPPPPPPPp....
    ....PPPPPPpp....
    .....PPPPpp.....
    ......PPpp......
    .......pp.......
    ................
    ................
    ................
    ................`);
})();

// Charms (belt): they stay in the belt and recharge as rooms are cleared.
(function charms() {
  def('pot_charmheal', autoOutline(parseArt('charmheal', `
    ...YY...
    ..Y..y..
    ..y..o..
    ..qq.q..
    .qwqPPp.
    .qqPPPp.
    ..PPPp..
    ...pp...`)), { sil: '2' });
  def('pot_charmshield', autoOutline(parseArt('charmshield', `
    ...YY...
    ..Y..y..
    ..y..o..
    .CCCCCc.
    .CwwCcc.
    .CwCccb.
    ..Cccb..
    ...cb...`)), { sil: '2' });
})();

// A star scroll (pickup and the library), door reward marks, the nemesis crown.
(function misc() {
  def('scroll_0', autoOutline(parseArt('scroll0', `
    ..........
    .NNNNNNNn.
    .nnnnnnnn.
    ..AAAAAe..
    ..AaYaae..
    ..AYyYae..
    ..AaYaae..
    ..Aaaaae..
    .NNNNNNNn.
    .nnnnnnnn.
    ..........`)));
  def('scroll_1', autoOutline(parseArt('scroll1', `
    ..........
    .NNNNNNNn.
    .nnnnnnnn.
    ..AAAAAe..
    ..AaaYae..
    ..AaYwYe..
    ..AaaYae..
    ..Aaaaae..
    .NNNNNNNn.
    .nnnnnnnn.
    ..........`)));
  // 5x5 marks on the doors of normal rooms: what clearing the room pays
  def('mm_coin', '.000.\n0yYy0\n0Yyo0\n0yoo0\n.000.');
  def('mm_heart', '00.00\n0qP0p\n0PPPp\n.0pp0\n..00.');
  def('mm_pot', '.000.\n.0c0.\n0CcB0\n0cBb0\n.000.');
  def('mm_scroll', '00000\n0Aae0\n0aYe0\n0Aae0\n00000');
  def('mm_gem', '.000.\n0CcB0\n0cBb0\n.0b0.\n..0..');
  def('mm_skull', '.00000.\n0LLLLl0\n0L0L0l0\n0LLLLl0\n.0lll0.\n..000..');
  // the nemesis wears a little crown
  def('crown_s', autoOutline(parseArt('crown_s', `
    .........
    .Y..Y..Y.
    .YY.Y.Yy.
    .YyYyYyy.
    .yyyyyyo.
    .oooooooo
    .........`)));
})();
