'use strict';
// Art for the special rooms: the star shrine, the fountain, the rescue cage, a Big Star,
// the star key, wall cracks, the critters you rescue and the minimap marks.
(function roomArt() {
  const A = (name, art, opts) => def(name, autoOutline(parseArt(name, art)), opts);

  // Star shrine: a stone pillar with a floating star
  A('shrine', `
    ................
    .......Y........
    ......YwY.......
    .......Y........
    ................
    ....LLLLLLLL....
    ....LlllllLm....
    .....LlllLm.....
    .....LlllLm.....
    .....LlllLm.....
    .....LlllLm.....
    .....LlllLm.....
    .....LlllLm.....
    ....LlllllLmm...
    ...LLllllllLmm..
    ...lmmmmmmmmmm..
    ................`);
  // Fountain: a stone basin with a spout of water
  const fountain = (k) => `
    ................................
    ...............C................
    ..............CwC...............
    .............C.C.C..............
    ............C..${k ? 'w' : 'C'}..C.............
    ...............l................
    ..............lLm...............
    ...LLLLLLLLLLLLLLLLLLLLLLLLLLL..
    ..LlCCCCCCCCCCCCCCCCCCCCCCCCClm.
    ..LCc${k ? 'w' : 'C'}CCCcCCCC${k ? 'C' : 'w'}CCCcCCCCC${k ? 'w' : 'C'}CCccCm.
    ..LCCcCCCCCCCcCCCCCCCCcCCCCCcCm.
    ..lLccccccccccccccccccccccccccm.
    ...lmmmmmmmmmmmmmmmmmmmmmmmmmm..
    ....mdddddddddddddddddddddddd...
    ................................`;
  A('fountain_0', fountain(0));
  A('fountain_1', fountain(1));
  // Rescue cage: bars in front of a little friend (drawn between two layers)
  A('cage_back', `
    ................
    .....NNNNNN.....
    ....NOOOOOON....
    ...NnnnnnnnnN...
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ...NNNNNNNNNNn..
    ...nnnnnnnnnnn..
    ................`);
  A('cage_bars', `
    ................
    ................
    ................
    ................
    ...m..m..m..m...
    ...l..l..l..l...
    ...l..l..l..l...
    ...l..l..l..l...
    ...l..l..l..l...
    ...l..l..l..l...
    ...l..l..l..l...
    ...m..m..m..m...
    ................
    ................
    ................`);
  // A Big Star (the hidden seventh one)
  A('bigstar', `
    ................
    .......YY.......
    ......YwwY......
    ......YwYy......
    .YYYYYwYyyyyyo..
    ..YwwwYYyyyyo...
    ...YwwYyyyyo....
    ....YwYyyyo.....
    ....YYyyyyo.....
    ...YYyyyyyyo....
    ...Yyyyooyyyo...
    ..Yyyo....oyyo..
    ..Yyo......ooo..
    ..yo........oo..
    ................
    ................`, { flip: false });
  // The star key (opens the vault)
  A('key', `
    ..........
    ...YY.....
    ..YwwY....
    ..YwYy....
    ...yyy....
    ....y.....
    ....yYY...
    ....y.....
    ....yYy...
    ..........`);
  // Cracks in a wall (a secret room lies behind)
  def('crack', `
    ..0.....
    ...0..0.
    ..0.00..
    .0...0..
    0...0...
    ...0....`);
  // Critters you rescue; they come to live in the Garden (two frames each)
  A('crit_chick_0', `
    ..........
    ...YYY....
    ..YY0YO...
    ..YYYYo...
    .YYYYYy...
    .yYYYYy...
    ..yyyy....
    ...O.O....
    ..........`);
  A('crit_chick_1', `
    ..........
    ..........
    ...YYY....
    ..YY0YO...
    .YYYYYo...
    .yYYYYy...
    ..yyyy....
    ..O...O...
    ..........`);
  A('crit_hedgehog_0', `
    ............
    ...n.n.n....
    ..nNnNnNn...
    .nNNNNNNNn..
    .NNNNNNNNsk.
    .nNNNNNNs0s.
    ..nnnnnnsks.
    ...k..k.....
    ............`);
  A('crit_hedgehog_1', `
    ............
    ............
    ...n.n.n....
    ..nNnNnNn...
    .nNNNNNNNsk.
    .NNNNNNNs0s.
    ..nnnnnnsks.
    ..k....k....
    ............`);
  A('crit_duck_0', `
    ...........
    ......YY...
    .....YY0O..
    .....YYYo..
    .YY.YYYY...
    .YYYYYYYy..
    ..yYYYYyy..
    ...yyyyy...
    ....O.O....
    ...........`);
  A('crit_duck_1', `
    ...........
    ...........
    ......YY...
    .....YY0O..
    .YY..YYYo..
    .YYYYYYYy..
    ..yYYYYyy..
    ...yyyyy...
    ...O...O...
    ...........`);
  // minimap and door marks of the special rooms (5x5, own outline)
  def('mm_shrine', '..0..\n.0Y0.\n0YwY0\n.0Y0.\n..0..');
  def('mm_altar', '.000.\n0Y000\n0Y0..\n0Y000\n.000.');
  def('mm_fount', '..0..\n.0C0.\n0CwC0\n0Ccc0\n.000.');
  def('mm_gamble', '00000\n0L0L0\n0LLL0\n0L0L0\n00000');
  def('mm_rescue', '00000\n0l0l0\n0lql0\n0l0l0\n00000');
  def('mm_champ', '0.0.0\n0Y0Y0\n0YYY0\n0RYR0\n00000');
  def('mm_lock', '.000.\n.0.0.\n00000\n0y0y0\n00000');
  def('mm_key', '.000.\n0Yw0.\n0YY00\n.00y0\n...00');
})();

// Colour-blind option: every enemy bullet colour also has its own shape.
(function cbBullets() {
  const RAMP = { pink: 'pPqw', cyan: 'bcCw', orange: 'oOYw', purple: '134w' };
  const SMALL = {
    pink: ['.0000.', '0lwhb0', '0wwwb0', '0hwbd0', '0bbdd0', '.0000.'],
    cyan: ['..00..', '.0hl0.', '0hlbb0', '0lbbd0', '.0bd0.', '..00..'],
    orange: ['000000', '0hhlb0', '0hlbb0', '0lbbd0', '0bbdd0', '000000'],
    purple: ['..00..', '00hl00', '0hlbb0', '0lbbd0', '00bd00', '..00..'],
  };
  const BIG = {
    pink: ['..0000..', '.0lhll0.', '0lhwwlb0', '0hwwwbb0', '0lwwwbd0', '0lbwbbd0', '.0bddd0.', '..0000..'],
    cyan: ['...00...', '..0hl0..', '.0hllb0.', '0hlllbb0', '0llbbbd0', '.0lbbd0.', '..0bd0..', '...00...'],
    orange: ['00000000', '0hhhllb0', '0hhllbb0', '0hllbbb0', '0llbbbd0', '0lbbbdd0', '0bbbddd0', '00000000'],
    purple: ['...00...', '...0l0..', '000hl000', '0hhllbb0', '0llbbbd0', '000bd000', '..0dd0..', '...00...'],
  };
  const paint = (rows, r) => rows.map(row => row.replace(/[dblh]/g, c => r['dblh'.indexOf(c)]));
  for (const k in RAMP) {
    def('ebcb_' + k, paint(SMALL[k], RAMP[k]));
    def('ebbcb_' + k, paint(BIG[k], RAMP[k]));
  }
})();
