'use strict';
// Game data: upgrades, lands, room layouts.

// unique: can only be owned once. Descriptions must fit the item banner.
const ITEMS = {
  rapid: { name: 'QUICK SPELL', desc: 'FASTER SHOTS', apply: p => { p.fireDelay *= 0.72; } },
  big: { name: 'BIG STAR', desc: 'BIGGER, STRONGER SHOTS', apply: p => { p.dmg += 1.5; p.bigShot = true; } },
  triple: { name: 'TRIPLE BEAM', desc: 'THREE SHOTS AT ONCE', apply: p => { p.shots += 2; p.fireDelay *= 1.12; } },
  bounce: { name: 'BOUNCY BALL', desc: 'SHOTS BOUNCE OFF WALLS', apply: p => { p.bounce += 2; } },
  pierce: { name: 'PIERCING ARROW', desc: 'SHOTS PIERCE THROUGH ENEMIES', apply: p => { p.pierce += 2; } },
  homing: { name: 'FIREFLY', desc: 'HOMING SHOTS', apply: p => { p.homing += 1; } },
  moon: { name: 'LITTLE MOON', desc: 'A MOON THAT ORBITS YOU', apply: p => { p.orbitals += 1; } },
  heart: { name: 'HEART BLOSSOM', desc: '+1 HEART AND A FULL HEAL', apply: p => { p.maxHp = Math.min(20, p.maxHp + 2); p.hp = p.maxHp; } },
  speed: { name: 'WIND BOOTS', desc: 'FASTER RUNNING AND ROLLING', apply: p => { p.speed *= 1.15; p.dashCd *= 0.75; } },
  magnet: { name: 'MAGNET', desc: 'PULLS TREASURE TOWARD YOU', unique: true, apply: p => { p.magnet = true; } },
  firework: { name: 'FIREWORKS', desc: 'SHOTS BURST INTO SPARKS ON HIT', apply: p => { p.fireworks += 1; } },
  honey: { name: 'HONEY POT', desc: 'EVERY 12TH DEFEATED ENEMY HEALS YOU', unique: true, apply: p => { p.honey = true; } },
  backshot: { name: 'BACK EYE', desc: 'YOU ALSO SHOOT BACKWARDS', unique: true, apply: p => { p.backshot = true; } },
  clover: { name: 'LUCKY CLOVER', desc: 'MORE LOOT, CHEAPER SHOP', apply: p => { p.luck += 1; } },
  scope: { name: 'TELESCOPE', desc: 'FASTER SHOTS THAT FLY FARTHER', apply: p => { p.shotSpeed *= 1.25; p.range *= 1.35; p.dmg += 0.5; } },
  stardust: { name: 'STARDUST', desc: 'ROLLING LEAVES HARMFUL STARDUST', unique: true, apply: p => { p.stardust = true; } },
  shield: { name: 'BUBBLE SHIELD', desc: 'BLOCKS ONE HIT IN EVERY ROOM', unique: true, apply: p => { p.shield = true; p.shieldUp = true; } },
};

// Lands. Floors past the third loop through them with rising difficulty.
const LANDS = [
  { theme: 'meadow', song: 'meadow', rooms: 8, slime: 'green', boss: 'king', bossName: 'SLIME KING',
    pool: [['slime', 4], ['bee', 2], ['shroom', 2], ['flower', 2]] },
  { theme: 'beach', song: 'beach', rooms: 10, slime: 'blue', boss: 'bcrab', bossName: 'GIANT CRAB',
    pool: [['slime', 3], ['bee', 1], ['crab', 3], ['flower', 2], ['jelly', 3]] },
  { theme: 'crystal', song: 'crystal', rooms: 11, slime: 'pink', boss: 'golem', bossName: 'CRYSTAL GOLEM',
    pool: [['slime', 2], ['bat', 3], ['shroom', 2], ['wisp', 3], ['crab', 1]] },
];

// Room interiors: 22 x 10. '.' floor, '#' rock, 'b' breakable, '~' pit, 'e' enemy slot.
// Door approaches (top/bottom centre, left/right middle) must stay open; checked at load.
const LAYOUTS = [
  `......................
   ..e................e..
   ......................
   ......#........#......
   .........e..e.........
   ......................
   ......#........#......
   ......................
   ..e................e..
   ......................`,
  `......................
   ...##............##...
   ...##..e......e..##...
   ......................
   .........e..e.........
   ......................
   ......................
   ...##..e......e..##...
   ...##............##...
   ......................`,
  `......................
   ..e................e..
   ......................
   .......~~~~~~~~.......
   .......~~~~~~~~.......
   .......~~~~~~~~.......
   .......~~~~~~~~.......
   ......................
   ..e.......e........e..
   ......................`,
  `......................
   .b.................b..
   .bb...e.......e...bb..
   ......................
   .........bbbb.........
   .........bbbb.........
   ......................
   .bb...e.......e...bb..
   .b.................b..
   ......................`,
  `......................
   .........e..e.........
   ..###............###..
   ..#....e......e....#..
   ......................
   ......................
   ..#....e......e....#..
   ..###............###..
   .........e..e.........
   ......................`,
  `......................
   .e..~~~~......~~~~..e.
   ....~~~~......~~~~....
   ......................
   ..........ee..........
   ......................
   ......................
   ....~~~~......~~~~....
   .e..~~~~......~~~~..e.
   ......................`,
  `......................
   ....#.....e.....#.....
   .e.....#......#.....e.
   ..........##..........
   ...#..............#...
   .....e..........e.....
   ..........##..........
   .e.....#......#.....e.
   ....#...........#.....
   ......................`,
  `......................
   ..e.......e........e..
   .....######..######...
   .....#............#...
   .....#....ee......#...
   .....#............#...
   .....######..######...
   ..e................e..
   ......................
   ......................`,
  `......................
   ..~~..........e...~~..
   ..~~..............~~..
   ......e......e........
   ..........~~..........
   ..........~~..........
   ........e......e......
   ..~~..............~~..
   ..~~..e...........~~..
   ......................`,
  `......................
   ..b....b......b....b..
   ......e.......e.......
   ..b..................b
   .....b....ee....b.....
   ......................
   ..b..................b
   ......e.......e.......
   ..b....b......b....b..
   ......................`,
  `......................
   .e.................e..
   ....~~~~~~..~~~~~~....
   ....~............~....
   ....~..e......e..~....
   ....~..e......e..~....
   ....~............~....
   ....~~~~~~..~~~~~~....
   .e.................e..
   ......................`,
  `......................
   .....e..........e.....
   ..#................#..
   ..#...bb......bb...#..
   ..#.......ee.......#..
   ..#.......ee.......#..
   ..#...bb......bb...#..
   ..#................#..
   .....e..........e.....
   ......................`,
  `......................
   ..e...#........#...e..
   ......#........#......
   ......#...ee...#......
   ......................
   ......................
   ......#...ee...#......
   ......#........#......
   ..e...#........#...e..
   ......................`,
  `......................
   ...e..b.......b..e....
   ..~~~~~.......~~~~~...
   ......................
   .......#..ee..#.......
   .......#..ee..#.......
   ......................
   ..~~~~~.......~~~~~...
   ...e..b.......b..e....
   ......................`,
  `......................
   ..e..~~.......~~..e...
   .....~~.......~~......
   .........e..e.........
   ..~~..............~~..
   ..~~..............~~..
   .........e..e.........
   .....~~.......~~......
   ..e..~~.......~~..e...
   ......................`,
  `......................
   ..e.................e.
   ...bbbbbb....bbbbbb...
   ......................
   ......e........e......
   ......e........e......
   ......................
   ...bbbbbb....bbbbbb...
   ..e.................e.
   ......................`,
  `......................
   .e...~~~~~..~~~~~..e..
   .....~~~~~..~~~~~.....
   .....~~~~~..~~~~~.....
   ......................
   ......................
   .....~~~~~..~~~~~.....
   .....~~~~~..~~~~~.....
   .e...~~~~~..~~~~~..e..
   ......................`,
  `......................
   ..e...................
   ...#...#......#...#...
   ..........e...........
   ...#...#......#...#...
   ......e.......e.......
   ...#...#......#...#...
   ...........e..........
   ...#...#......#...#.e.
   ......................`,
  `......................
   ..e................e..
   .........#..#.........
   .......#......#.......
   .....#....ee....#.....
   .....#....ee....#.....
   .......#......#.......
   .........#..#.........
   ..e................e..
   ......................`,
  `......................
   .e....b..........b..e.
   ......b..######..b....
   ......b..........b....
   ...#......e..e........
   ...#..................
   ......b..........b....
   ......b..######..b....
   .e....b..........b..e.
   ......................`,
  `......................
   .~~~.....e..e.....~~~.
   .~~~..............~~~.
   ..e..............e....
   .......~~....~~.......
   .......~~....~~.......
   ..e..............e....
   .~~~..............~~~.
   .~~~.....e..e.....~~~.
   ......................`,
  `......................
   ..e...............e...
   ....#............#....
   ....#....e..e....#....
   ....#............#....
   ....#............#....
   ....#............#....
   ....##############....
   ..e...............e...
   ......................`,
  `......................
   ...b...e.....#....e...
   ..~~.............b....
   ..~~....#.............
   .........e...e...##...
   ..##..................
   .......b.....~~.......
   ..e..........~~....e..
   ......#...........b...
   ......................`,
].map(s => s.split('\n').map(r => r.trim()));
// Boss arena: four free-standing rocks for cover, no corner pockets to hide in.
const BOSS_LAYOUT = [
  '......................',
  '......................',
  '...#..............#...',
  '......................',
  '......................',
  '......................',
  '......................',
  '...#..............#...',
  '......................',
  '......................',
];

// Garden: permanent upgrades bought with vault coins. cost per level.
const UPGRADES = [
  { id: 'hp', name: 'HEART SEED', desc: '+1 HEART WHEN A RUN STARTS', icon: 'icon_heart', cost: [24, 60, 120] },
  { id: 'dmg', name: 'SPELL POWER', desc: '+12% DAMAGE', icon: 'icon_big', cost: [30, 70, 140] },
  { id: 'rate', name: 'QUICK HANDS', desc: 'SHOOT 10% FASTER', icon: 'icon_rapid', cost: [30, 70, 140] },
  { id: 'multi', name: 'EXTRA STAR', desc: 'ONE MORE PROJECTILE PER SHOT', icon: 'icon_triple', cost: [150, 350] },
  { id: 'speed', name: 'SWIFT FEET', desc: '+6% SPEED', icon: 'icon_speed', cost: [20, 50, 100] },
  { id: 'bank', name: 'PIGGY BANK', desc: 'KEEP MORE OF YOUR COINS FOREVER', icon: 'icon_bag', cost: [30, 80, 160] },
  { id: 'luck', name: 'LUCKY STAR', desc: 'MORE LOOT, CHEAPER SHOP', icon: 'icon_clover', cost: [30, 70, 140] },
  { id: 'charge', name: 'STAR HEART', desc: 'STARFALL CHARGES FASTER', icon: 'icon_stardust', cost: [24, 60, 120] },
  { id: 'belt', name: 'POTION BELT', desc: '+1 BELT SLOT, START WITH A POTION', icon: 'pot_regen', cost: [30, 70, 140] },
];

// Wands: unlocked forever with vault coins, one is chosen before each run.
// Stats multiply the hero's base values; kind picks the projectile behaviour.
const WANDS = {
  wand: { name: 'STAR WAND', desc: 'TRUSTY AND BALANCED', cost: 0, dmg: 1, rate: 1, speed: 1, range: 1 },
  scatter: { name: 'SPARK SCATTER', desc: 'A SPRAY OF SPARKS UP CLOSE', cost: 50, dmg: 0.55, rate: 1.5, speed: 1.1, range: 0.62, fan: 3 },
  bubble: { name: 'BUBBLE BLASTER', desc: 'A STREAM OF SPEEDY BUBBLES', cost: 70, dmg: 0.42, rate: 0.42, speed: 0.85, range: 0.85 },
  boomer: { name: 'MOON BOOMERANG', desc: 'PIERCES ALL AND COMES BACK', cost: 90, dmg: 1.1, rate: 1.85, speed: 1, range: 0.8 },
  chain: { name: 'LIGHTNING ROD', desc: 'SHOTS ARC TO NEARBY ENEMIES', cost: 110, dmg: 0.85, rate: 1.1, speed: 1.25, range: 1 },
  comet: { name: 'COMET STAFF', desc: 'SLOW COMETS THAT EXPLODE', cost: 130, dmg: 1.5, rate: 2.2, speed: 0.72, range: 1.05 },
};

// Belt items: potions and the turret kit. t: effect length in seconds.
const POTIONS = {
  regen: { name: 'REGENERATION', desc: 'HEALS THREE HEARTS OVER TIME', t: 9, price: 7 },
  haste: { name: 'HASTE', desc: 'SHOOT AND RUN FASTER', t: 9, price: 6 },
  power: { name: 'POWER', desc: 'YOUR SPELLS HIT MUCH HARDER', t: 9, price: 6 },
  guard: { name: 'GUARD', desc: 'NOTHING CAN HURT YOU', t: 5, price: 7 },
  turret: { name: 'STAR TURRET', desc: 'A TOWER THAT SHOOTS FOR YOU', t: 20, price: 8 },
};
const POTION_IDS = Object.keys(POTIONS);

// Difficulty, chosen before a run (the host chooses in co-op). vault: reward multiplier.
const DIFFS = [
  { name: 'EASY', desc: 'A GENTLE STROLL', hp: 0.7, count: -1, elite: -0.04, pace: 0.88, bullet: 0.9, vault: 0.75 },
  { name: 'NORMAL', desc: 'THE WAY IT IS MEANT TO BE', hp: 1, count: 0, elite: 0, pace: 1, bullet: 1, vault: 1 },
  { name: 'HARD', desc: 'TOUGHER, FASTER, MORE OF THEM', hp: 1.35, count: 1, elite: 0.08, pace: 1.12, bullet: 1.12, vault: 1.3 },
  { name: 'STARBREAKER', desc: 'ONLY FOR TRUE STAR WIZARDS', hp: 1.75, count: 2, elite: 0.16, pace: 1.22, bullet: 1.22, vault: 1.6 },
];
// Co-op makes every fight bigger: more health, a few more foes, more elites.
const DIFF = () => DIFFS[G.diff];
const crewHp = (boss) => 1 + (boss ? 0.65 : 0.5) * (G.players.length - 1);
