'use strict';
// Magyar: Wildgrove (a túlélő mód). Adds to the table of lang_hu.js.
(() => {
  const T = LANG.hu.table;
  const tier = { WOODEN: 'FA', STONE: 'KŐ', COPPER: 'RÉZ', IRON: 'VAS', CRYSTAL: 'KRISTÁLY', STAR: 'CSILLAG' };
  const tool = { PICKAXE: 'CSÁKÁNY', AXE: 'BALTA', SHOVEL: 'ÁSÓ', HOE: 'KAPA', SWORD: 'KARD', SPEAR: 'LÁNDZSA', CAP: 'SAPKA', TUNIC: 'TUNIKA', BOOTS: 'CSIZMA', DOOR: 'AJTÓ', WALL: 'FAL' };
  const tierF = { WOODEN: 'FA', STONE: 'KŐ', COPPER: 'RÉZ', IRON: 'VAS', CRYSTAL: 'KRISTÁLY', STAR: 'CSILLAG', LEATHER: 'BŐR' };
  for (const t in tierF) for (const k in tool) T[t + ' ' + k] = tierF[t] + (k === 'PICKAXE' || k === 'AXE' || k === 'SHOVEL' || k === 'HOE' || k === 'SWORD' || k === 'SPEAR' || k === 'CAP' || k === 'TUNIC' || k === 'BOOTS' ? '' : ' ') + tool[k];
  Object.assign(T, {
    // items
    'WOOD': 'FA', 'STICK': 'BOT', 'STONE': 'KŐ', 'PLANT FIBER': 'NÖVÉNYROST', 'FLINT': 'KOVAKŐ', 'COAL': 'SZÉN', 'COPPER ORE': 'RÉZÉRC', 'IRON ORE': 'VASÉRC',
    'COPPER BAR': 'RÉZRÚD', 'IRON BAR': 'VASRÚD', 'CRYSTAL': 'KRISTÁLY', 'STAR ORE': 'CSILLAGÉRC', 'STAR BAR': 'CSILLAGRÚD', 'SAND': 'HOMOK', 'CLAY': 'AGYAG',
    'GLASS': 'ÜVEG', 'BRICK': 'TÉGLA', 'LEATHER': 'BŐR', 'WOOL': 'GYAPJÚ', 'FEATHER': 'TOLL', 'BONE': 'CSONT', 'SLIME': 'SLEJM', 'STRING': 'ZSINÓR', 'EGG': 'TOJÁS',
    'HONEY': 'MÉZ', 'FLOUR': 'LISZT', 'SUGAR': 'CUKOR', 'RED PETALS': 'PIROS SZIROM', 'YELLOW PETALS': 'SÁRGA SZIROM', 'BLUE PETALS': 'KÉK SZIROM',
    'WHITE PETALS': 'FEHÉR SZIROM', 'PURPLE PETALS': 'LILA SZIROM', 'EMBER': 'PARA', 'OBSIDIAN': 'OBSZIDIÁN', 'PEARL': 'GYÖNGY', 'SHELL': 'KAGYLÓ',
    'CACTUS FRUIT': 'KAKTUSZGYÜMÖLCS', 'ICE SHARD': 'JÉGSZILÁNK', 'GLOW BERRY': 'FÉNYBOGYÓ', 'BERRIES': 'BOGYÓK', 'APPLE': 'ALMA', 'CARROT': 'SÁRGARÉPA',
    'POTATO': 'KRUMPLI', 'WHEAT': 'BÚZA', 'PUMPKIN': 'TÖK', 'RED MUSHROOM': 'PIROS GOMBA', 'BROWN MUSHROOM': 'BARNA GOMBA', 'RAW FISH': 'NYERS HAL',
    'RAW MEAT': 'NYERS HÚS', 'COOKED FISH': 'SÜLT HAL', 'STEAK': 'SZELET HÚS', 'BREAD': 'KENYÉR', 'BAKED POTATO': 'SÜLT KRUMPLI', 'HEARTY STEW': 'ERŐS PÖRKÖLT',
    'BERRY PIE': 'BOGYÓS PITE', 'CARROT SOUP': 'RÉPALEVES', 'HONEY CAKE': 'MÉZESKALÁCS', 'WHEAT SEEDS': 'BÚZAMAG', 'CARROT SEEDS': 'RÉPAMAG',
    'POTATO EYES': 'KRUMPLISZEM', 'PUMPKIN SEEDS': 'TÖKMAG', 'BERRY CUTTING': 'BOGYÓDUGVÁNY', 'HUNTING BOW': 'VADÁSZÍJ', 'STAR LONGBOW': 'CSILLAGÍJ',
    'ARROW': 'NYÍL', 'SPARK WAND': 'SZIKRAPÁLCA', 'FROST WAND': 'FAGYPÁLCA', 'STARFALL WAND': 'CSILLAGHULLÁS-PÁLCA', 'FISHING ROD': 'HORGÁSZBOT',
    'WATERING CAN': 'LOCSOLÓKANNA', 'BUCKET': 'VÖDÖR', 'WATER BUCKET': 'VÍZES VÖDÖR', 'SHEARS': 'OLLÓ', 'TORCH': 'FÁKLYA', 'LANTERN': 'LÁMPÁS',
    'CHEST': 'LÁDA', 'BARREL': 'HORDÓ', 'WORKBENCH': 'MUNKAPAD', 'FURNACE': 'KEMENCE', 'ANVIL': 'ÜLLŐ', 'ALCHEMY TABLE': 'ALKÍMIAASZTAL', 'LOOM': 'SZŐSZÉK',
    'CAMPFIRE': 'TÁBORTŰZ', 'BED': 'ÁGY', 'TABLE': 'ASZTAL', 'CHAIR': 'SZÉK', 'SIGN': 'TÁBLA', 'BOOKSHELF': 'KÖNYVESPOLC', 'SCARECROW': 'MADÁRIJESZTŐ',
    'FENCE': 'KERÍTÉS', 'WOODEN DOOR': 'FAAJTÓ', 'IRON DOOR': 'VASAJTÓ', 'WOOD WALL': 'FAFAL', 'STONE WALL': 'KŐFAL', 'BRICK WALL': 'TÉGLAFAL',
    'SANDSTONE WALL': 'HOMOKKŐFAL', 'ICE WALL': 'JÉGFAL', 'GLASS WALL': 'ÜVEGFAL', 'IRON WALL': 'VASFAL', 'WOOD FLOOR': 'FAPADLÓ', 'STONE TILES': 'KŐLAP',
    'BRICK FLOOR': 'TÉGLAPADLÓ', 'RED CARPET': 'PIROS SZŐNYEG', 'BLUE CARPET': 'KÉK SZŐNYEG', 'GREEN CARPET': 'ZÖLD SZŐNYEG', 'DIRT PATH': 'FÖLDÚT',
    'OAK SAPLING': 'TÖLGYCSEMETE', 'BIRCH SAPLING': 'NYÁRCSEMETE', 'PINE SAPLING': 'FENYŐCSEMETE', 'PALM SAPLING': 'PÁLMACSEMETE', 'JUNGLE SAPLING': 'DZSUNGELCSEMETE',
    // the world
    'OAK TREE': 'TÖLGYFA', 'BIRCH TREE': 'NYÍRFA', 'PINE TREE': 'FENYŐFA', 'SNOWY PINE': 'HAVAS FENYŐ', 'PALM TREE': 'PÁLMAFA', 'JUNGLE TREE': 'DZSUNGELFA',
    'DEAD TREE': 'ELHALT FA', 'WILLOW': 'FŰZFA', 'CACTUS': 'KAKTUSZ', 'GIANT MUSHROOM': 'ÓRIÁSGOMBA', 'BOULDER': 'SZIKLATÖMB', 'PEBBLES': 'KAVICSOK',
    'COAL VEIN': 'SZÉNEÉR', 'COPPER VEIN': 'RÉZÉR', 'IRON VEIN': 'VASÉR', 'CRYSTAL CLUSTER': 'KRISTÁLYCSOPORT', 'ICE CHUNK': 'JÉGTÖMB', 'CLAY DEPOSIT': 'AGYAGLELŐHELY',
    'SAND DUNE': 'HOMOKDŰNE', 'TALL GRASS': 'MAGAS FŰ', 'FERN': 'PÁFRÁNY', 'REEDS': 'NÁD', 'DRY BUSH': 'SZÁRAZ BOKOR', 'BERRY BUSH': 'BOGYÓSBOKOR',
    'RIPE BERRY BUSH': 'ÉRETT BOGYÓSBOKOR', 'RED FLOWER': 'PIROS VIRÁG', 'YELLOW FLOWER': 'SÁRGA VIRÁG', 'BLUE FLOWER': 'KÉK VIRÁG', 'WHITE FLOWER': 'FEHÉR VIRÁG',
    'PURPLE FLOWER': 'LILA VIRÁG', 'GLOWCAP': 'FÉNYGOMBA', 'LILY PAD': 'VÍZILILIOM', 'WILD WHEAT': 'VADBÚZA', 'WILD CARROT': 'VADRÉPA', 'PUMPKIN PATCH': 'TÖKFOLT',
    'SHELLS': 'KAGYLÓK', 'CARROTS': 'SÁRGARÉPÁK', 'POTATOES': 'KRUMPLIK', 'PUMPKIN VINE': 'TÖKINDA', 'ROCK': 'SZIKLA', 'FROZEN ROCK': 'FAGYOTT SZIKLA',
    'SANDSTONE': 'HOMOKKŐ', 'ASH ROCK': 'HAMUKŐ', 'OPEN DOOR': 'NYITOTT AJTÓ', 'OPEN IRON DOOR': 'NYITOTT VASAJTÓ', 'WELL': 'KÚT', 'CAVE STAIRS': 'BARLANGLÉPCSŐ',
    'STAIRS UP': 'LÉPCSŐ FEL', 'OLD ALTAR': 'RÉGI OLTÁR', 'OLD PILLAR': 'RÉGI OSZLOP', 'OLD CHEST': 'RÉGI LÁDA', 'BONES': 'CSONTOK', 'COBWEB': 'PÓKHÁLÓ',
    'STEAM VENT': 'GŐZNYÍLÁS', 'STAR RIFT': 'CSILLAGHASADÉK', 'COAL SEAM': 'SZÉNTELEP', 'COPPER SEAM': 'RÉZTELEP', 'IRON SEAM': 'VASTELEP', 'CRYSTAL SEAM': 'KRISTÁLYTELEP',
    'STAR SEAM': 'CSILLAGTELEP', 'WILD POTATOES': 'VADKRUMPLI', 'DEEP WATER': 'MÉLY VÍZ', 'SHALLOW WATER': 'SEKÉLY VÍZ', 'GRASS': 'FŰ', 'DIRT': 'FÖLD', 'SNOW': 'HÓ',
    'STONE FLOOR': 'KŐPADLÓ', 'MUD': 'SÁR', 'JUNGLE FLOOR': 'DZSUNGELTALAJ', 'ASH': 'HAMU', 'LAVA': 'LÁVA', 'TILLED SOIL': 'MEGMUNKÁLT FÖLD', 'ICE': 'JÉG',
    'CAVE FLOOR': 'BARLANGPADLÓ', 'MOSSY STONE': 'MOHOS KŐ', 'PATH': 'ÚT', 'OCEAN': 'ÓCEÁN', 'BEACH': 'STRAND', 'MEADOW': 'RÉT', 'FOREST': 'ERDŐ', 'JUNGLE': 'DZSUNGEL',
    'DESERT': 'SIVATAG', 'SNOWFIELD': 'HÓMEZŐ', 'SWAMP': 'MOCSÁR', 'MOUNTAINS': 'HEGYEK', 'HIGHLAND': 'FENNSÍK', 'VOLCANO': 'VULKÁN',
    // creatures
    'SHEEP': 'BIRKA', 'CHICKEN': 'TYÚK', 'SKELETON': 'CSONTVÁZ', 'BAT': 'DENEVÉR',
    // screens
    'WILDGROVE': 'WILDGROVE', 'A WORLD OF YOUR OWN': 'A SAJÁT VILÁGOD', 'NO WORLDS YET. MAKE ONE!': 'MÉG NINCS VILÁG. KÉSZÍTS EGYET!', 'LOOKING FOR WORLDS...': 'VILÁGOK KERESÉSE...',
    'NEW WORLD': 'ÚJ VILÁG', 'IMPORT': 'BETÖLTÉS', 'EXPORT': 'MENTÉS FÁJLBA', 'DELETE': 'TÖRLÉS', 'JOIN WITH CODE': 'CSATLAKOZÁS KÓDDAL', 'PUBLIC WORLDS': 'NYILVÁNOS VILÁGOK',
    'PEACEFUL': 'BÉKÉS', 'SURVIVAL': 'TÚLÉLŐ', 'DAY #': '# NAP', 'DAY # # MIN': '# NAP  # PERC', 'WORLD NAME': 'VILÁG NEVE', 'SEED (EMPTY FOR RANDOM)': 'MAG (ÜRES: VÉLETLEN)',
    'YOUR NAME': 'A NEVED', 'YOUR HERO': 'A HŐSÖD', 'SKIN <>': 'BŐR <>', 'HAIR <>': 'HAJ <>', 'SHIRT <>': 'PÓLÓ <>', 'MODE: PEACEFUL': 'MÓD: BÉKÉS', 'MODE: SURVIVAL': 'MÓD: TÚLÉLŐ',
    'CREATE': 'LÉTREHOZ', 'CANCEL': 'MÉGSE', 'LOADING THE WORLD...': 'A VILÁG BETÖLTÉSE...', 'WELCOME TO *': 'ÜDVÖZÖL: *', 'WELCOME BACK': 'ÜDV ÚJRA',
    'PRESS DELETE AGAIN TO ERASE *': 'NYOMD MEG MÉGEGYSZER A TÖRLÉST: *', 'WORLD DELETED': 'VILÁG TÖRÖLVE', 'IMPORTED *': 'BETÖLTVE: *', 'THAT IS NOT A WORLD FILE': 'EZ NEM VILÁGFÁJL',
    'SAVED * AS A FILE': 'MENTVE FÁJLBA: *', 'STORAGE IS BLOCKED IN THIS BROWSER': 'A BÖNGÉSZŐ NEM ENGED TÁROLNI', 'COULD NOT OPEN THAT WORLD': 'EZT A VILÁGOT NEM LEHETETT MEGNYITNI',
    'BACKPACK': 'HÁTIZSÁK', 'WORN': 'VISELT', 'DEFENSE #': 'VÉDELEM #', 'CRAFTING': 'BARKÁCSOLÁS', 'NEAR: *': 'KÖZELBEN: *', 'NEAR: NOTHING': 'KÖZELBEN: SEMMI', 'WHEEL SCROLLS': 'GÖRGETÉS: KEREK',
    '#-# OF #   WHEEL SCROLLS': '#-# / #   GÖRGETÉS: KEREK', 'MADE *': 'ELKÉSZÜLT: *', 'PAUSED': 'SZÜNET', 'RESUME': 'FOLYTATÁS', 'SAVE NOW': 'MENTÉS MOST', 'WORLD SAVED': 'VILÁG MENTVE',
    'SAVE FAILED': 'SIKERTELEN MENTÉS', 'EXPORT WORLD': 'VILÁG EXPORTÁLÁSA', 'WORLD FILE SAVED': 'VILÁGFÁJL MENTVE', 'CONTROLS': 'IRÁNYÍTÁS', 'HIDE CONTROLS': 'IRÁNYÍTÁS ELREJTÉSE',
    'SAVE AND QUIT': 'MENTÉS ÉS KILÉPÉS', 'LEAVE WORLD': 'KILÉPÉS A VILÁGBÓL', 'PLAY WITH FRIENDS': 'JÁTÉK BARÁTOKKAL', 'FRIENDS: CODE *': 'BARÁTOK: KÓD *', 'YOU FELL': 'ELESTÉL',
    'YOUR PACK WAITS WHERE YOU FELL': 'A HÁTIZSÁKOD ODA HULLOTT, AHOL ELESTÉL', 'GET UP': 'FELKELEK', 'WASD  MOVE (SHIFT RUNS)': 'WASD  MOZGÁS (SHIFT: FUTÁS)', 'LEFT CLICK  MINE / HIT (HOLD)': 'BAL KATTINTÁS  BÁNYÁSZ / ÜT (TARTSD)',
    'RIGHT CLICK  USE / PLACE / EAT': 'JOBB KATTINTÁS  HASZNÁL / LERAK / EVÉS', '1-9 OR WHEEL  HOTBAR': '1-9 VAGY GÖRGŐ  GYORSSÁV', 'E  BACKPACK AND CRAFTING': 'E  HÁTIZSÁK ÉS BARKÁCSOLÁS',
    'Q  DROP ONE': 'Q  EGYET ELDOB', 'ENTER  CHAT (ONLINE)': 'ENTER  CSEVEG (ONLINE)', 'ESC  PAUSE': 'ESC  SZÜNET', 'YOUR WORLD STAYS ON YOUR DEVICE.': 'A VILÁGOD A SAJÁT ESZKÖZÖDÖN MARAD.',
    'FRIENDS JOIN WHILE THIS GAME IS OPEN.': 'A BARÁTOK AMÍG EZ A JÁTÉK NYITVA VAN, CSATLAKOZHATNAK.', 'OPEN PRIVATE (CODE ONLY)': 'PRIVÁT (CSAK KÓDDAL)', 'OPEN PUBLIC (LISTED)': 'NYILVÁNOS (LISTÁBAN)',
    'CODE': 'KÓD', 'LISTED IN PUBLIC WORLDS': 'SZEREPEL A NYILVÁNOS LISTÁN', 'PRIVATE: ONLY WITH THE CODE': 'PRIVÁT: CSAK A KÓDDAL', 'MAKE PRIVATE': 'LEGYEN PRIVÁT', 'MAKE PUBLIC': 'LEGYEN NYILVÁNOS',
    'CLOSE TO FRIENDS': 'BEZÁRÁS A BARÁTOK ELŐL', 'JOIN A WORLD': 'CSATLAKOZÁS EGY VILÁGHOZ', 'FRIEND CODE (5 LETTERS)': 'BARÁT KÓDJA (5 BETŰ)', 'ASK YOUR FRIEND FOR THEIR CODE': 'KÉRD EL A BARÁTOD KÓDJÁT',
    'CONNECT': 'CSATLAKOZÁS', 'CONNECTING...': 'CSATLAKOZÁS...', 'NO ONE ANSWERED. CHECK THE CODE.': 'SENKI NEM VÁLASZOLT. NÉZD MEG A KÓDOT.', 'LOOKING FOR OPEN WORLDS...': 'NYITOTT VILÁGOK KERESÉSE...',
    'NO OPEN WORLDS RIGHT NOW': 'MOST NINCS NYITOTT VILÁG', 'REFRESH': 'FRISSÍT', 'THAT WORLD IS FULL': 'EZ A VILÁG MEGTELT', 'THE HOST CLOSED THE WORLD': 'A HOSZT BEZÁRTA A VILÁGOT',
    'LOST THE CONNECTION': 'MEGSZAKADT A KAPCSOLAT', 'PLEASE RELOAD THE PAGE: NEW VERSION': 'TÖLTSD ÚJRA AZ OLDALT: ÚJ VERZIÓ', 'JOINED *': 'CSATLAKOZTÁL: *', '* JOINED!': '* CSATLAKOZOTT!',
    '* LEFT': '* KILÉPETT', '* JOINED': '* CSATLAKOZOTT', 'OPEN TO FRIENDS: *': 'NYITVA A BARÁTOKNAK: *', 'USE': 'HASZNÁL', 'BAG': 'ZSÁK',
    'NEEDS A BETTER PICKAXE': 'JOBB CSÁKÁNY KELL', 'NEEDS A BETTER TOOL': 'JOBB SZERSZÁM KELL', 'SPAWN POINT SET': 'ÚJRAKEZDÉSI PONT BEÁLLÍTVA', 'GOOD MORNING': 'JÓ REGGELT', 'THE ALTAR HUMS...': 'AZ OLTÁR ZÜMMÖG...',
    'FRESH WATER (+HP)': 'FRISS VÍZ (+ÉLET)', 'PLANT ON TILLED SOIL': 'MEGMUNKÁLT FÖLDRE VESS', 'YUCK! RAW FOOD': 'FUJ! NYERS ÉTEL', 'DOWN INTO THE CAVES': 'LE A BARLANGOKBA', 'BACK TO THE SURFACE': 'VISSZA A FELSZÍNRE',
    'NO ARROWS': 'NINCS NYÍL', 'FISHING...': 'HORGÁSZÁS...', 'CAUGHT A FISH!': 'HALAT FOGTÁL!', 'THE LINE SNAPPED BACK': 'A ZSINÓR VISSZACSAPÓDOTT', 'DAY # BEGINS': '# NAP KEZDŐDIK',
    'SIGN: *': 'TÁBLA: *', 'EASY': 'KÖNNYŰ', 'NORMAL': 'NORMÁL', 'HARD': 'NEHÉZ', 'DIFFICULTY: *': 'NEHÉZSÉG: *', 'DIFFICULTY': 'NEHÉZSÉG', 'STAR WARDEN': 'CSILLAGŐR', 'THE STAR WARDEN AWAKENS!': 'FELÉBRED A CSILLAGŐR!', 'THE WARDEN IS ALREADY HERE': 'AZ ŐR MÁR ITT VAN', 'THE RIFT WANTS 3 STAR BARS': 'A HASADÉK 3 CSILLAGRÚDAT KÉR', 'F2  PHOTO': 'F2  FÉNYKÉP', 'PHOTO SAVED': 'FÉNYKÉP MENTVE', 'A NEW GAME ON THE TITLE SCREEN: WILDGROVE': 'ÚJ JÁTÉK A FŐMENÜBEN: WILDGROVE', 'AN ENDLESS SURVIVAL WORLD: CHOP, BUILD, FARM, FIGHT': 'VÉGTELEN TÚLÉLŐ VILÁG: VÁGJ, ÉPÍTS, TERMELJ, HARCOLJ', 'PLAY WITH FRIENDS, SAVE AND SHARE YOUR WORLDS': 'JÁTSSZ BARÁTOKKAL, MENTSD ÉS OSZD MEG A VILÁGAIDAT', 'RESTORE OLDER SAVE': 'RÉGEBBI MENTÉS VISSZATÖLTÉSE', 'RESTORED THE OLDER SAVE': 'RÉGEBBI MENTÉS VISSZATÖLTVE', 'NO OLDER SAVE YET': 'MÉG NINCS RÉGEBBI MENTÉS', 'PRESS AGAIN: * GOES BACK TO AN OLDER SAVE': 'NYOMD MEG ÚJRA: * RÉGEBBI MENTÉSRE ÁLL VISSZA', 'THIS WORLD IS OPEN IN ANOTHER TAB': 'EZ A VILÁG MÁR NYITVA VAN EGY MÁSIK LAPON', 'ALREADY SHEARED': 'MÁR NYÍRTAD', 'NOT NOW': 'MOST NEM', 'TOO CROWDED': 'TÚL SOK ÁLLAT', 'A NEW *!': 'ÚJ ÁLLAT: *!', 'SLIME KING': 'SLEJMKIRÁLY', 'THE SLIME KING WAKES!': 'FELÉBRED A SLEJMKIRÁLY!', 'THE KING IS ALREADY HERE': 'A KIRÁLY MÁR ITT VAN', 'THE ALTAR WANTS 5 SLIME': 'AZ OLTÁR 5 SLEJMET KÉR', 'ONLY THE HOST CAN CALL IT': 'CSAK A HOSZT HÍVHATJA', 'THE * FALLS!': 'ELESETT: *', 'SETTINGS': 'BEÁLLÍTÁSOK', 'MUSIC': 'ZENE', 'SOUND EFFECTS': 'HANGEFFEKTEK', 'LENGTH OF A DAY': 'A NAP HOSSZA', 'SHORT DAYS': 'RÖVID NAPOK', 'NORMAL DAYS': 'NORMÁL NAPOK', 'LONG DAYS': 'HOSSZÚ NAPOK', 'CREATURES': 'LÉNYEK', 'DANGEROUS': 'VESZÉLYES', 'KEEP BACKPACK': 'HÁTIZSÁK MEGMARAD', 'ON': 'BE', 'OFF': 'KI', 'DONE': 'KÉSZ', 'THE HOST DECIDES THE WORLD RULES': 'A VILÁG SZABÁLYAIT A HOSZT ÁLLÍTJA', '# / 10': '# / 10', 'IT STARTS TO RAIN': 'ESNI KEZD', 'THE RAIN STOPS': 'ELÁLL AZ ESŐ', 'WALK WITH WASD OR THE LEFT STICK': 'JÁRJ A WASD-VEL VAGY A BAL BOTTAL', 'HOLD LEFT CLICK ON A TREE TO CHOP IT': 'TARTSD A BAL GOMBOT EGY FÁN: KIVÁGOD', 'PRESS E: MAKE STICKS AND A WORKBENCH': 'NYOMJ E-T: KÉSZÍTS BOTOT ÉS MUNKAPADOT', 'SELECT THE BENCH, RIGHT CLICK TO PLACE IT': 'VÁLASZD KI A PADOT, JOBB KATTINTÁSSAL TEDD LE', 'STAND NEXT TO IT AND PRESS E: CRAFT A PICKAXE': 'ÁLLJ MELLÉ ÉS NYOMJ E-T: KÉSZÍTS CSÁKÁNYT', 'NIGHT IS DANGEROUS. TORCHES AND A WALL KEEP YOU SAFE': 'AZ ÉJSZAKA VESZÉLYES. FÁKLYÁK ÉS FAL VÉDENEK', 'DAY *': '* NAP', 'CAVE': 'BARLANG',
  });
})();
