'use strict';
// ---------- Lantern Woods (Lantern Light) ----------
// The woods are dusk-dim, never black. Each hero's own lantern lights about three tiles round
// them; a shot lights a lamp post (T_LAMP, layout 'l') for LAMP_T seconds, and a cleared room
// keeps its lamps lit. Foes out in the dark show only their eyes; bullets, tells and rings
// always stay above the dark. The light is worked out on every screen from the same things
// (heroes, lit lamps, doors, foes in a tell), so lightAt() agrees for game logic in co-op.
const LAMP_T = 20, LAMP_R = 64, HERO_R = 48, DUSK = 0.72;

// A park lamp: a little roof, warm glass, a wooden post rising a few pixels over the tile above.
LA('lamp_1', `
  ................
  .......32.......
  ......3221......
  ....33222211....
  ....11111111....
  .....1wYYy1.....
  .....1YYyy1.....
  .....1YyyO1.....
  .....1yyOO1.....
  ....32222211....
  ......N2n1......
  .......Nn.......
  .......Nn.......
  .......Nn.......
  .......Nn.......
  .......Nn.......
  .......Nn.......
  .......Nn.......
  .......Nn.......
  ......NNnu......
  .....NNnnnu.....
  ...hGNnnnnuGg...
  ................`);
// unlit: the cold glass keeps one glint of the dusk
LA('lamp_0', `
  ................
  .......32.......
  ......3221......
  ....33222211....
  ....11111111....
  .....1VvvV1.....
  .....1vvV11.....
  .....1vV111.....
  .....1V1111.....
  ....32222211....
  ......N2n1......
  .......Nn.......
  .......Nn.......
  .......Nn.......
  .......Nn.......
  .......Nn.......
  .......Nn.......
  .......Nn.......
  .......Nn.......
  ......NNnu......
  .....NNnnnu.....
  ...hGNnnnnuGg...
  ................`);

// ---------- Lamps ----------
const lampTile = (t) => t === T_LAMP || t === T_LAMPON;
// Where the lamps stand. Rock tiles of a plain fight room may become lamps, and every room gets
// at least two; boss and warden rooms get one near each corner. Seeded by the room, so every
// screen builds the same woods.
const LAMP_CORNERS = { big: [[5, 4], [18, 4], [5, 9], [18, 9]], calm: [[3, 3], [20, 3], [3, 10], [20, 10]] };
function lampOk(room, c, r) {
  const i = r * COLS + c;
  if (room.tiles[i] !== T_FLOOR || c < 2 || c > 21 || r < 3 || r > 10) return false;
  if ((c >= 10 && c <= 13) || (r >= 5 && r <= 8 && (c <= 3 || c >= 20))) return false; // the ways in and out
  for (const [x, y] of room.slots || []) if (Math.abs(x - (c * 16 + 8)) < 24 && Math.abs(y - (OY + r * 16 + 8)) < 24) return false;
  for (let k = 0; k < room.tiles.length; k++) if (lampTile(room.tiles[k]) && Math.abs(k % COLS - c) < 4 && Math.abs(((k / COLS) | 0) - r) < 3) return false;
  return keepsJoined(room, i, T_LAMP);
}
function lampsBuild(room) {
  const t = room.tiles;
  if (room.type === 'slide') return;
  let n = 0;
  for (let i = 0; i < t.length; i++) if (t[i] === T_LAMP) n++;
  if (room.type === 'boss' || room.type === 'warden' || room.type === 'arena' || !room.flip) {
    for (const [c, r] of LAMP_CORNERS[room.flip ? 'big' : 'calm']) if (lampOk(room, c, r)) t[r * COLS + c] = T_LAMP;
    return;
  }
  // a few rocks turn into lamp posts
  for (let i = 0; i < t.length && n < 3; i++) if (t[i] === T_ROCK && hash(i, 21, room.seed) % 5 === 0) { t[i] = T_LAMP; n++; }
  for (let k = 0; n < 2 && k < 40; k++) {
    const h = hash(k, 22, room.seed), c = 3 + h % 18, r = 3 + (h >>> 8) % 8;
    if (lampOk(room, c, r)) { t[r * COLS + c] = T_LAMP; n++; }
  }
}
// A shot hit a lamp: it lights (again) for LAMP_T seconds. Only where the game runs.
function lampHit(room, c, r) {
  if (NET.role === 'client') return;
  const was = tileAt(room, c, r);
  setTile(room, c, r, T_LAMPON); // setTile stamps the time, which is also the lamp's clock
  if (was === T_LAMPON) return;
  const x = c * 16 + 8, y = OY + r * 16 - 1;
  burst(x, y, 10, ['Y', 'y', 'O'], 50, 0.5, { g: -30 });
  Audio_.sfx('lamp');
  if (!Save.flags.lampTip) { Save.flags.lampTip = true; Save.write(); toast('A LIT LAMP KEEPS THE DARK AWAY'); }
}
const lampLeft = (room, i) => LAMP_T - (G.time - ((room.tAt && room.tAt.get(i)) || -99));

// ---------- The light ----------
const TELL_STATES = new Set(['tele', 'aim', 'charge', 'rise']);
function woodsLight(room) {
  lightReset(0); // a sparse dither reads as a mesh, so the dusk stays whole and the pools do the work
  for (const p of G.players) if (!p.dead) lightAdd(p.x, p.y - 6, alive(p) ? HERO_R + 16 * (p.wick || 0) : 24);
  const t = room.tiles;
  for (let i = 0; i < t.length; i++) if (t[i] === T_LAMPON) lightAdd((i % COLS) * 16 + 8, OY + ((i / COLS) | 0) * 16 - 1, LAMP_R);
  for (const d in room.doors) if (!hiddenDoor(room, d)) { const [x, y] = ENTRY[d]; lightAdd(x, y, room.cleared ? 28 : 16); }
  for (const e of G.enemies) {
    if (e.dead) continue;
    if (e.boss || EDEF[e.type].warden) lightAdd(e.x, e.y - 12, 28);
    else if (TELL_STATES.has(e.state) || glintAt(e)) lightAdd(e.x, e.y - 6, 20);
  }
  for (const k of room.pickups) lightAdd(k.x, k.y - 3, 10);
}
// Two dots where a foe's face is, for foes the light does not reach.
function foeEyes(e, ox, oy) {
  const s = enemySprite(e), z = Math.round(e.z || 0);
  const x = Math.round(ox + e.x), y = Math.round(oy + e.y - z - s.h * 0.55), gap = Math.max(2, Math.round(s.w / 7));
  const blink = Math.floor(G.time * 0.7 + e.x * 0.13) % 9 === 0 && (G.time * 5 + e.y) % 1 < 0.5;
  if (blink) return;
  rect(x - gap - 1, y, 2, 1, 'Y'); rect(x + gap - 1, y, 2, 1, 'Y');
}

LAND_MECH.lantern = {
  build: lampsBuild,
  // host / solo: lamps gutter out; a cleared room lights them all for good
  update(dt, room) {
    const t = room.tiles;
    for (let i = 0; i < t.length; i++) {
      if (t[i] === T_LAMP && room.cleared) {
        setTile(room, i % COLS, (i / COLS) | 0, T_LAMPON);
        burst((i % COLS) * 16 + 8, OY + ((i / COLS) | 0) * 16 - 1, 6, ['Y', 'y'], 40, 0.4, { g: -30 });
        Audio_.sfx('lamp');
      } else if (t[i] === T_LAMPON && !room.cleared && lampLeft(room, i) <= 0) {
        setTile(room, i % COLS, (i / COLS) | 0, T_LAMP);
        poof((i % COLS) * 16 + 8, OY + ((i / COLS) | 0) * 16 - 2);
        Audio_.sfx('snuff');
      }
    }
  },
  every(dt, room) {
    woodsLight(room);
    if (!Save.flags.woods) { Save.flags.woods = true; Save.write(); } // unlocks the BRIGHT WOODS setting
  },
  drawLayer(ox, oy, room, layer) {
    if (layer === 0) {
      // a lamp near its end flickers (the tile time is known on every screen)
      const t = room.tiles;
      for (let i = 0; i < t.length; i++) {
        if (t[i] !== T_LAMPON || room.cleared) continue;
        const left = lampLeft(room, i);
        if (left > 3 || Math.floor(G.time * (left < 1.5 ? 14 : 7)) % 3) continue;
        const sp = S('lamp_0'), c = i % COLS, r = (i / COLS) | 0;
        drawS(sp, ox + c * 16, oy + OY + r * 16 + 16 - sp.h);
      }
      return;
    }
    if (layer !== 1) return;
    const amb = LIGHT.amb, n = LIGHT.n;
    for (const a of AMB) if (a.life > 0 && a.kind === 'ffly') lightAdd(a.x, a.y, 7); // fireflies glow, for the eye only
    drawLight(ox, oy, Save.settings.bright ? DUSK * 0.4 : DUSK); // BRIGHT WOODS: seen, not played
    LIGHT.amb = amb; LIGHT.n = n;
    // what must never hide in the dark: tells, rings, dazed sparkles, and foes' eyes
    drawMarkers(ox, oy);
    for (const e of G.enemies) {
      if (e.dead) continue;
      const g = glintAt(e), z = Math.round(e.z || 0);
      if (g && Math.floor(e.anim * 16) % 2) drawS(S('sparkle_0'), ox + e.x + g[0] - 1, oy + e.y + g[1] - z - 1);
      if (e.stag > 0) { const s = enemySprite(e); for (let k = 0; k < 3; k++) { const a = e.anim * 5 + k * 2.1; drawS(S('sparkle_c'), ox + e.x + Math.round(Math.cos(a) * 12) - 1, oy + e.y - z + 1 - s.h + Math.round(Math.sin(a) * 3) - 2); } }
      if (lightAt(e.x, e.y - 6) === 0) foeEyes(e, ox, oy);
    }
    // light finds the cracks of a secret door
    if (room.hidden) for (const d in room.hidden) {
      const [x, y] = d === 'u' ? [188, OY + 18] : d === 'd' ? [188, OY + 196] : d === 'l' ? [4, OY + 104] : [372, OY + 104];
      if (lightAt(x + 4, y + 4) < 2) continue;
      drawS(S('crack'), ox + x, oy + y);
      if (Math.floor(G.time * 3) % 2) drawS(S('sparkle_0'), ox + x + 3, oy + y - 2);
    }
  },
};

// ---------- Rooms ----------
LAND_LAYOUTS.lantern = {
  // Lantern Alley: two rows of posts along the lane
  alley: `......................
    ..e.......ee.......e..
    ...l....l....l....l...
    #....................#
    ......................
    ......................
    #....................#
    ...l....l....l....l...
    ..e.......ee.......e..
    ......................`,
  // Hollow Log: a fallen trunk to run through, a lamp at each end
  hollow: `......................
    ..e.......e........e..
    ......................
    ...#######..#######...
    ...l..............l...
    ........e....e........
    ...#######..#######...
    ......................
    ..e.......e........e..
    ......................`,
  // Mushroom Ring: a fairy ring of breakable caps round a lamp
  ring: `......................
    ..e................e..
    ........bb..bb........
    ......b........b......
    .....b....l.....b.....
    .....b.....e....b.....
    ......b........b......
    ........bb..bb........
    ..e................e..
    ......................`,
  // Firefly Glade: a still pond with lamps round its bank
  glade: `......................
    ..e..l.........l..e...
    ......................
    ........~~~~~~........
    .......~~~~~~~~.......
    ...e...~~~~~~~~...e...
    ........~~~~~~........
    ......................
    ..e..l.........l..e...
    ......................`,
  // Creek Crossing: a brook with one bridge, lit at both ends
  creek: `.......~~.............
    ..e....~~....e........
    .......~~.............
    ......l~~l............
    ......................
    ......................
    .......~~l.......e....
    .......~~.............
    ..e....~~.........e...
    .......~~.............`,
  // Scarecrow Field: rows of pumpkin patches, a post in the middle
  field: `......................
    ..e..l....ee....l..e..
    ......................
    ..bbbb.bbb..bbb.bbbb..
    ..........#...........
    ......................
    ..bbbb.bbb..bbb.bbbb..
    ......................
    ..e..l....ee....l..e..
    ......................`,
};
for (const k in LAND_LAYOUTS.lantern) LAND_LAYOUTS.lantern[k] = LAND_LAYOUTS.lantern[k].split('\n').map(r => r.trim());
